/** \file
 *  This C source file was generated by $ANTLR version !Unknown version!
 *
 *     -  From the grammar source file : ext/wongi_turtle/Turtle.g
 *     -                            On : 2012-06-26 14:15:27
 *     -                for the parser : TurtleParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */


	#include <ruby.h>
	#include "extern.h"

	#define COLLECTOR_DOCUMENT rb_funcall( collector, rb_intern("document"), 0 )
	#define MATCH(string) printf("matched " string "\n");

	#define RDF_NS "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	#define RDF_TYPE RDF_NS "type"


/* End of Header action.
 * =============================================================================
 */
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "TurtleParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pTurtleParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pTurtleParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pTurtleParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pTurtleParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER		    
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO		    
#undef		DBG

#define	    PARSER							ctx->pParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		MEMOIZE(ri,si)					RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT							PARSER->tstream
#define	    STRSTREAM						INPUT
#define		ISTREAM							INPUT->istream
#define		INDEX()							ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   TurtleParserTokenNames[11+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "IDENT",
        (pANTLR3_UINT8) "URI",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'.'",
        (pANTLR3_UINT8) "'@prefix'",
        (pANTLR3_UINT8) "':'",
        (pANTLR3_UINT8) "'@base'",
        (pANTLR3_UINT8) "';'",
        (pANTLR3_UINT8) "','",
        (pANTLR3_UINT8) "'a'",
        (pANTLR3_UINT8) "'_:'"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static TurtleParser_document_return	document    (pTurtleParser ctx, VALUE collector);
static TurtleParser_statement_return	statement    (pTurtleParser ctx, VALUE collector);
static TurtleParser_directive_return	directive    (pTurtleParser ctx, VALUE collector);
static TurtleParser_namespace_declaration_return	namespace_declaration    (pTurtleParser ctx, VALUE collector);
static TurtleParser_base_declaration_return	base_declaration    (pTurtleParser ctx, VALUE collector);
static TurtleParser_triples_return	triples    (pTurtleParser ctx, VALUE collector);
static TurtleParser_predicate_object_list_return	predicate_object_list    (pTurtleParser ctx, VALUE collector, VALUE subject);
static TurtleParser_predicate_object_pair_return	predicate_object_pair    (pTurtleParser ctx, VALUE collector, VALUE subject);
static TurtleParser_object_list_return	object_list    (pTurtleParser ctx, VALUE collector, VALUE subject, VALUE predicate);
static TurtleParser_subject_return	subject    (pTurtleParser ctx, VALUE collector);
static TurtleParser_verb_return	verb    (pTurtleParser ctx, VALUE collector);
static TurtleParser_predicate_return	predicate    (pTurtleParser ctx, VALUE collector);
static TurtleParser_object_return	object    (pTurtleParser ctx, VALUE collector);
static TurtleParser_resource_return	resource    (pTurtleParser ctx, VALUE collector);
static TurtleParser_qname_return	qname    (pTurtleParser ctx, VALUE collector);
static TurtleParser_blank_return	blank    (pTurtleParser ctx, VALUE collector);
static TurtleParser_uri_return	uri    (pTurtleParser ctx, VALUE collector);
static void	TurtleParserFree(pTurtleParser ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "ext/wongi_turtle/Turtle.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new TurtleParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pTurtleParser
TurtleParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return TurtleParserNewSSD(instream, NULL);
}

/** \brief Create a new TurtleParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pTurtleParser
TurtleParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pTurtleParser ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pTurtleParser) ANTLR3_CALLOC(1, sizeof(TurtleParser));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in TurtleParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our TurtleParser interface
     */
    ctx->document	= document;
    ctx->statement	= statement;
    ctx->directive	= directive;
    ctx->namespace_declaration	= namespace_declaration;
    ctx->base_declaration	= base_declaration;
    ctx->triples	= triples;
    ctx->predicate_object_list	= predicate_object_list;
    ctx->predicate_object_pair	= predicate_object_pair;
    ctx->object_list	= object_list;
    ctx->subject	= subject;
    ctx->verb	= verb;
    ctx->predicate	= predicate;
    ctx->object	= object;
    ctx->resource	= resource;
    ctx->qname	= qname;
    ctx->blank	= blank;
    ctx->uri	= uri;
    ctx->free			= TurtleParserFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */
    ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);
    ctx->vectors	= antlr3VectorFactoryNew(0);
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = TurtleParserTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 TurtleParserFree(pTurtleParser ctx)
 {
    /* Free any scope memory
     */
    
    ctx->vectors->close(ctx->vectors);
    /* We created the adaptor so we must free it
     */
    ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return TurtleParserTokenNames; 
}

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_statement_in_document82  */
static	ANTLR3_BITWORD FOLLOW_statement_in_document82_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000532) };
static  ANTLR3_BITSET_LIST FOLLOW_statement_in_document82	= { FOLLOW_statement_in_document82_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_directive_in_statement97  */
static	ANTLR3_BITWORD FOLLOW_directive_in_statement97_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_directive_in_statement97	= { FOLLOW_directive_in_statement97_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_triples_in_statement102  */
static	ANTLR3_BITWORD FOLLOW_triples_in_statement102_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_triples_in_statement102	= { FOLLOW_triples_in_statement102_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_7_in_statement107  */
static	ANTLR3_BITWORD FOLLOW_7_in_statement107_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_7_in_statement107	= { FOLLOW_7_in_statement107_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_namespace_declaration_in_directive118  */
static	ANTLR3_BITWORD FOLLOW_namespace_declaration_in_directive118_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_namespace_declaration_in_directive118	= { FOLLOW_namespace_declaration_in_directive118_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_base_declaration_in_directive124  */
static	ANTLR3_BITWORD FOLLOW_base_declaration_in_directive124_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_base_declaration_in_directive124	= { FOLLOW_base_declaration_in_directive124_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_8_in_namespace_declaration138  */
static	ANTLR3_BITWORD FOLLOW_8_in_namespace_declaration138_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_8_in_namespace_declaration138	= { FOLLOW_8_in_namespace_declaration138_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENT_in_namespace_declaration140  */
static	ANTLR3_BITWORD FOLLOW_IDENT_in_namespace_declaration140_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENT_in_namespace_declaration140	= { FOLLOW_IDENT_in_namespace_declaration140_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_9_in_namespace_declaration142  */
static	ANTLR3_BITWORD FOLLOW_9_in_namespace_declaration142_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000530) };
static  ANTLR3_BITSET_LIST FOLLOW_9_in_namespace_declaration142	= { FOLLOW_9_in_namespace_declaration142_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_uri_in_namespace_declaration144  */
static	ANTLR3_BITWORD FOLLOW_uri_in_namespace_declaration144_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_uri_in_namespace_declaration144	= { FOLLOW_uri_in_namespace_declaration144_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_10_in_base_declaration161  */
static	ANTLR3_BITWORD FOLLOW_10_in_base_declaration161_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000530) };
static  ANTLR3_BITSET_LIST FOLLOW_10_in_base_declaration161	= { FOLLOW_10_in_base_declaration161_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_uri_in_base_declaration163  */
static	ANTLR3_BITWORD FOLLOW_uri_in_base_declaration163_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_uri_in_base_declaration163	= { FOLLOW_uri_in_base_declaration163_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_subject_in_triples180  */
static	ANTLR3_BITWORD FOLLOW_subject_in_triples180_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002530) };
static  ANTLR3_BITSET_LIST FOLLOW_subject_in_triples180	= { FOLLOW_subject_in_triples180_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_object_list_in_triples183  */
static	ANTLR3_BITWORD FOLLOW_predicate_object_list_in_triples183_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_object_list_in_triples183	= { FOLLOW_predicate_object_list_in_triples183_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_object_pair_in_predicate_object_list197  */
static	ANTLR3_BITWORD FOLLOW_predicate_object_pair_in_predicate_object_list197_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000802) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_object_pair_in_predicate_object_list197	= { FOLLOW_predicate_object_pair_in_predicate_object_list197_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_11_in_predicate_object_list202  */
static	ANTLR3_BITWORD FOLLOW_11_in_predicate_object_list202_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002530) };
static  ANTLR3_BITSET_LIST FOLLOW_11_in_predicate_object_list202	= { FOLLOW_11_in_predicate_object_list202_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_object_pair_in_predicate_object_list204  */
static	ANTLR3_BITWORD FOLLOW_predicate_object_pair_in_predicate_object_list204_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000802) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_object_pair_in_predicate_object_list204	= { FOLLOW_predicate_object_pair_in_predicate_object_list204_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_verb_in_predicate_object_pair221  */
static	ANTLR3_BITWORD FOLLOW_verb_in_predicate_object_pair221_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004530) };
static  ANTLR3_BITSET_LIST FOLLOW_verb_in_predicate_object_pair221	= { FOLLOW_verb_in_predicate_object_pair221_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_object_list_in_predicate_object_pair224  */
static	ANTLR3_BITWORD FOLLOW_object_list_in_predicate_object_pair224_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_object_list_in_predicate_object_pair224	= { FOLLOW_object_list_in_predicate_object_pair224_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_object_in_object_list246  */
static	ANTLR3_BITWORD FOLLOW_object_in_object_list246_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001002) };
static  ANTLR3_BITSET_LIST FOLLOW_object_in_object_list246	= { FOLLOW_object_in_object_list246_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_12_in_object_list253  */
static	ANTLR3_BITWORD FOLLOW_12_in_object_list253_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004530) };
static  ANTLR3_BITSET_LIST FOLLOW_12_in_object_list253	= { FOLLOW_12_in_object_list253_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_object_in_object_list257  */
static	ANTLR3_BITWORD FOLLOW_object_in_object_list257_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001002) };
static  ANTLR3_BITSET_LIST FOLLOW_object_in_object_list257	= { FOLLOW_object_in_object_list257_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_resource_in_subject280  */
static	ANTLR3_BITWORD FOLLOW_resource_in_subject280_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_resource_in_subject280	= { FOLLOW_resource_in_subject280_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_in_verb306  */
static	ANTLR3_BITWORD FOLLOW_predicate_in_verb306_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_in_verb306	= { FOLLOW_predicate_in_verb306_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_13_in_verb315  */
static	ANTLR3_BITWORD FOLLOW_13_in_verb315_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_13_in_verb315	= { FOLLOW_13_in_verb315_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_resource_in_predicate334  */
static	ANTLR3_BITWORD FOLLOW_resource_in_predicate334_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_resource_in_predicate334	= { FOLLOW_resource_in_predicate334_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_resource_in_object354  */
static	ANTLR3_BITWORD FOLLOW_resource_in_object354_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_resource_in_object354	= { FOLLOW_resource_in_object354_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_blank_in_object363  */
static	ANTLR3_BITWORD FOLLOW_blank_in_object363_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_blank_in_object363	= { FOLLOW_blank_in_object363_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_qname_in_resource388  */
static	ANTLR3_BITWORD FOLLOW_qname_in_resource388_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_qname_in_resource388	= { FOLLOW_qname_in_resource388_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_uri_in_resource396  */
static	ANTLR3_BITWORD FOLLOW_uri_in_resource396_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_uri_in_resource396	= { FOLLOW_uri_in_resource396_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENT_in_qname424  */
static	ANTLR3_BITWORD FOLLOW_IDENT_in_qname424_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENT_in_qname424	= { FOLLOW_IDENT_in_qname424_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_9_in_qname426  */
static	ANTLR3_BITWORD FOLLOW_9_in_qname426_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_9_in_qname426	= { FOLLOW_9_in_qname426_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENT_in_qname430  */
static	ANTLR3_BITWORD FOLLOW_IDENT_in_qname430_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENT_in_qname430	= { FOLLOW_IDENT_in_qname430_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_14_in_blank456  */
static	ANTLR3_BITWORD FOLLOW_14_in_blank456_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_14_in_blank456	= { FOLLOW_14_in_blank456_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENT_in_blank458  */
static	ANTLR3_BITWORD FOLLOW_IDENT_in_blank458_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENT_in_blank458	= { FOLLOW_IDENT_in_blank458_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_URI_in_uri481  */
static	ANTLR3_BITWORD FOLLOW_URI_in_uri481_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_URI_in_uri481	= { FOLLOW_URI_in_uri481_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start document
 * ext/wongi_turtle/Turtle.g:27:1: document[VALUE collector] : ( statement[collector] )* ;
 */
static TurtleParser_document_return
document(pTurtleParser ctx, VALUE collector)
{   
    TurtleParser_document_return retval;
    ANTLR3_UINT32 document_StartIndex;
    pANTLR3_BASE_TREE root_0;

    TurtleParser_statement_return statement1;
    #undef	RETURN_TYPE_statement1
    #define	RETURN_TYPE_statement1 TurtleParser_statement_return


    /* Initialize rule variables
     */
    document_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(1)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    statement1.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        // ext/wongi_turtle/Turtle.g:27:27: ( ( statement[collector] )* )
        // ext/wongi_turtle/Turtle.g:27:29: ( statement[collector] )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // ext/wongi_turtle/Turtle.g:27:29: ( statement[collector] )*

            for (;;)
            {
                int alt1=2;
                switch ( LA(1) ) 
                {
                case IDENT:
                case URI:
                case 8:
                case 10:
                	{
                		alt1=1;
                	}
                    break;

                }

                switch (alt1) 
                {
            	case 1:
            	    // ext/wongi_turtle/Turtle.g:27:29: statement[collector]
            	    {
            	        FOLLOWPUSH(FOLLOW_statement_in_document82);
            	        statement1=statement(ctx, collector);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledocumentEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, statement1.tree);

            	    }
            	    break;

            	default:
            	    goto loop1;	/* break out of the loop */
            	    break;
                }
            }
            loop1: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruledocumentEx; /* Prevent compiler warnings */
    ruledocumentEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end document */

/** 
 * $ANTLR start statement
 * ext/wongi_turtle/Turtle.g:29:1: statement[VALUE collector] : ( directive[collector] | triples[collector] ) '.' ;
 */
static TurtleParser_statement_return
statement(pTurtleParser ctx, VALUE collector)
{   
    TurtleParser_statement_return retval;
    ANTLR3_UINT32 statement_StartIndex;
    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal4;
    TurtleParser_directive_return directive2;
    #undef	RETURN_TYPE_directive2
    #define	RETURN_TYPE_directive2 TurtleParser_directive_return

    TurtleParser_triples_return triples3;
    #undef	RETURN_TYPE_triples3
    #define	RETURN_TYPE_triples3 TurtleParser_triples_return

    pANTLR3_BASE_TREE char_literal4_tree;

    /* Initialize rule variables
     */
    statement_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(2)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    char_literal4       = NULL;
    directive2.tree = NULL;

    triples3.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    char_literal4_tree   = NULL;


    retval.tree  = NULL;
    {
        // ext/wongi_turtle/Turtle.g:29:28: ( ( directive[collector] | triples[collector] ) '.' )
        // ext/wongi_turtle/Turtle.g:29:30: ( directive[collector] | triples[collector] ) '.'
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // ext/wongi_turtle/Turtle.g:29:30: ( directive[collector] | triples[collector] )
            {
                int alt2=2;
                switch ( LA(1) ) 
                {
                case 8:
                case 10:
                	{
                		alt2=1;
                	}
                    break;
                case IDENT:
                case URI:
                	{
                		alt2=2;
                	}
                    break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 2;
                    EXCEPTION->state        = 0;


                    goto rulestatementEx;
                }

                switch (alt2) 
                {
            	case 1:
            	    // ext/wongi_turtle/Turtle.g:29:32: directive[collector]
            	    {
            	        FOLLOWPUSH(FOLLOW_directive_in_statement97);
            	        directive2=directive(ctx, collector);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulestatementEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, directive2.tree);

            	    }
            	    break;
            	case 2:
            	    // ext/wongi_turtle/Turtle.g:29:55: triples[collector]
            	    {
            	        FOLLOWPUSH(FOLLOW_triples_in_statement102);
            	        triples3=triples(ctx, collector);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulestatementEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, triples3.tree);

            	    }
            	    break;

                }
            }
            char_literal4 = (pANTLR3_COMMON_TOKEN) MATCHT(7, &FOLLOW_7_in_statement107); 
            if  (HASEXCEPTION())
            {
                goto rulestatementEx;
            }

            char_literal4_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal4));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal4_tree);


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulestatementEx; /* Prevent compiler warnings */
    rulestatementEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end statement */

/** 
 * $ANTLR start directive
 * ext/wongi_turtle/Turtle.g:31:1: directive[VALUE collector] : ( namespace_declaration[collector] | base_declaration[collector] );
 */
static TurtleParser_directive_return
directive(pTurtleParser ctx, VALUE collector)
{   
    TurtleParser_directive_return retval;
    ANTLR3_UINT32 directive_StartIndex;
    pANTLR3_BASE_TREE root_0;

    TurtleParser_namespace_declaration_return namespace_declaration5;
    #undef	RETURN_TYPE_namespace_declaration5
    #define	RETURN_TYPE_namespace_declaration5 TurtleParser_namespace_declaration_return

    TurtleParser_base_declaration_return base_declaration6;
    #undef	RETURN_TYPE_base_declaration6
    #define	RETURN_TYPE_base_declaration6 TurtleParser_base_declaration_return


    /* Initialize rule variables
     */
    directive_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(3)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    namespace_declaration5.tree = NULL;

    base_declaration6.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        {
            //  ext/wongi_turtle/Turtle.g:32:2: ( namespace_declaration[collector] | base_declaration[collector] )
            
            ANTLR3_UINT32 alt3;

            alt3=2;

            switch ( LA(1) ) 
            {
            case 8:
            	{
            		alt3=1;
            	}
                break;
            case 10:
            	{
            		alt3=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 3;
                EXCEPTION->state        = 0;


                goto ruledirectiveEx;
            }

            switch (alt3) 
            {
        	case 1:
        	    // ext/wongi_turtle/Turtle.g:32:4: namespace_declaration[collector]
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_namespace_declaration_in_directive118);
        	        namespace_declaration5=namespace_declaration(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledirectiveEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, namespace_declaration5.tree);

        	    }
        	    break;
        	case 2:
        	    // ext/wongi_turtle/Turtle.g:33:4: base_declaration[collector]
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_base_declaration_in_directive124);
        	        base_declaration6=base_declaration(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledirectiveEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, base_declaration6.tree);

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruledirectiveEx; /* Prevent compiler warnings */
    ruledirectiveEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end directive */

/** 
 * $ANTLR start namespace_declaration
 * ext/wongi_turtle/Turtle.g:36:1: namespace_declaration[VALUE collector] : '@prefix' IDENT ':' uri[collector] ;
 */
static TurtleParser_namespace_declaration_return
namespace_declaration(pTurtleParser ctx, VALUE collector)
{   
    TurtleParser_namespace_declaration_return retval;
    ANTLR3_UINT32 namespace_declaration_StartIndex;
    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    string_literal7;
    pANTLR3_COMMON_TOKEN    IDENT8;
    pANTLR3_COMMON_TOKEN    char_literal9;
    TurtleParser_uri_return uri10;
    #undef	RETURN_TYPE_uri10
    #define	RETURN_TYPE_uri10 TurtleParser_uri_return

    pANTLR3_BASE_TREE string_literal7_tree;
    pANTLR3_BASE_TREE IDENT8_tree;
    pANTLR3_BASE_TREE char_literal9_tree;

    /* Initialize rule variables
     */
    namespace_declaration_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(4)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    string_literal7       = NULL;
    IDENT8       = NULL;
    char_literal9       = NULL;
    uri10.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    string_literal7_tree   = NULL;
    IDENT8_tree   = NULL;
    char_literal9_tree   = NULL;


    retval.tree  = NULL;
    {
        // ext/wongi_turtle/Turtle.g:37:2: ( '@prefix' IDENT ':' uri[collector] )
        // ext/wongi_turtle/Turtle.g:38:2: '@prefix' IDENT ':' uri[collector]
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            string_literal7 = (pANTLR3_COMMON_TOKEN) MATCHT(8, &FOLLOW_8_in_namespace_declaration138); 
            if  (HASEXCEPTION())
            {
                goto rulenamespace_declarationEx;
            }

            string_literal7_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, string_literal7));
            ADAPTOR->addChild(ADAPTOR, root_0, string_literal7_tree);

            IDENT8 = (pANTLR3_COMMON_TOKEN) MATCHT(IDENT, &FOLLOW_IDENT_in_namespace_declaration140); 
            if  (HASEXCEPTION())
            {
                goto rulenamespace_declarationEx;
            }

            IDENT8_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, IDENT8));
            ADAPTOR->addChild(ADAPTOR, root_0, IDENT8_tree);

            char_literal9 = (pANTLR3_COMMON_TOKEN) MATCHT(9, &FOLLOW_9_in_namespace_declaration142); 
            if  (HASEXCEPTION())
            {
                goto rulenamespace_declarationEx;
            }

            char_literal9_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal9));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal9_tree);

            FOLLOWPUSH(FOLLOW_uri_in_namespace_declaration144);
            uri10=uri(ctx, collector);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulenamespace_declarationEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, uri10.tree);
            {

                		VALUE rbPrefix = rb_str_new2( (IDENT8->getText(IDENT8))->chars );
                		VALUE rbFull = uri10.ruby_uri;

                		VALUE document = COLLECTOR_DOCUMENT;
                		VALUE rbNamespaces = rb_funcall( document, rb_intern("namespaces"), 0 );
                		rb_hash_aset( rbNamespaces, rbPrefix, rbFull );
                	
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulenamespace_declarationEx; /* Prevent compiler warnings */
    rulenamespace_declarationEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end namespace_declaration */

/** 
 * $ANTLR start base_declaration
 * ext/wongi_turtle/Turtle.g:49:1: base_declaration[VALUE collector] : '@base' uri[collector] ;
 */
static TurtleParser_base_declaration_return
base_declaration(pTurtleParser ctx, VALUE collector)
{   
    TurtleParser_base_declaration_return retval;
    ANTLR3_UINT32 base_declaration_StartIndex;
    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    string_literal11;
    TurtleParser_uri_return uri12;
    #undef	RETURN_TYPE_uri12
    #define	RETURN_TYPE_uri12 TurtleParser_uri_return

    pANTLR3_BASE_TREE string_literal11_tree;

    /* Initialize rule variables
     */
    base_declaration_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(5)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    string_literal11       = NULL;
    uri12.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    string_literal11_tree   = NULL;


    retval.tree  = NULL;
    {
        // ext/wongi_turtle/Turtle.g:50:2: ( '@base' uri[collector] )
        // ext/wongi_turtle/Turtle.g:51:2: '@base' uri[collector]
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            string_literal11 = (pANTLR3_COMMON_TOKEN) MATCHT(10, &FOLLOW_10_in_base_declaration161); 
            if  (HASEXCEPTION())
            {
                goto rulebase_declarationEx;
            }

            string_literal11_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, string_literal11));
            ADAPTOR->addChild(ADAPTOR, root_0, string_literal11_tree);

            FOLLOWPUSH(FOLLOW_uri_in_base_declaration163);
            uri12=uri(ctx, collector);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulebase_declarationEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, uri12.tree);
            {

                		VALUE rbDocument = COLLECTOR_DOCUMENT;
                		rb_funcall( rbDocument, rb_intern("base="), 1, uri12.ruby_uri );
                	
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulebase_declarationEx; /* Prevent compiler warnings */
    rulebase_declarationEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end base_declaration */

/** 
 * $ANTLR start triples
 * ext/wongi_turtle/Turtle.g:58:1: triples[VALUE collector] : subject[collector] predicate_object_list[collector, $subject.node] ;
 */
static TurtleParser_triples_return
triples(pTurtleParser ctx, VALUE collector)
{   
    TurtleParser_triples_return retval;
    ANTLR3_UINT32 triples_StartIndex;
    pANTLR3_BASE_TREE root_0;

    TurtleParser_subject_return subject13;
    #undef	RETURN_TYPE_subject13
    #define	RETURN_TYPE_subject13 TurtleParser_subject_return

    TurtleParser_predicate_object_list_return predicate_object_list14;
    #undef	RETURN_TYPE_predicate_object_list14
    #define	RETURN_TYPE_predicate_object_list14 TurtleParser_predicate_object_list_return


    /* Initialize rule variables
     */
    triples_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(6)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    subject13.tree = NULL;

    predicate_object_list14.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        // ext/wongi_turtle/Turtle.g:59:2: ( subject[collector] predicate_object_list[collector, $subject.node] )
        // ext/wongi_turtle/Turtle.g:60:2: subject[collector] predicate_object_list[collector, $subject.node]
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_subject_in_triples180);
            subject13=subject(ctx, collector);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruletriplesEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, subject13.tree);
            FOLLOWPUSH(FOLLOW_predicate_object_list_in_triples183);
            predicate_object_list14=predicate_object_list(ctx, collector, subject13.node);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruletriplesEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, predicate_object_list14.tree);

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruletriplesEx; /* Prevent compiler warnings */
    ruletriplesEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end triples */

/** 
 * $ANTLR start predicate_object_list
 * ext/wongi_turtle/Turtle.g:63:1: predicate_object_list[VALUE collector, VALUE subject] : predicate_object_pair[collector, subject] ( ';' predicate_object_pair[collector, subject] )* ;
 */
static TurtleParser_predicate_object_list_return
predicate_object_list(pTurtleParser ctx, VALUE collector, VALUE subject)
{   
    TurtleParser_predicate_object_list_return retval;
    ANTLR3_UINT32 predicate_object_list_StartIndex;
    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal16;
    TurtleParser_predicate_object_pair_return predicate_object_pair15;
    #undef	RETURN_TYPE_predicate_object_pair15
    #define	RETURN_TYPE_predicate_object_pair15 TurtleParser_predicate_object_pair_return

    TurtleParser_predicate_object_pair_return predicate_object_pair17;
    #undef	RETURN_TYPE_predicate_object_pair17
    #define	RETURN_TYPE_predicate_object_pair17 TurtleParser_predicate_object_pair_return

    pANTLR3_BASE_TREE char_literal16_tree;

    /* Initialize rule variables
     */
    predicate_object_list_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(7)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    char_literal16       = NULL;
    predicate_object_pair15.tree = NULL;

    predicate_object_pair17.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    char_literal16_tree   = NULL;


    retval.tree  = NULL;
    {
        // ext/wongi_turtle/Turtle.g:64:2: ( predicate_object_pair[collector, subject] ( ';' predicate_object_pair[collector, subject] )* )
        // ext/wongi_turtle/Turtle.g:65:2: predicate_object_pair[collector, subject] ( ';' predicate_object_pair[collector, subject] )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_predicate_object_pair_in_predicate_object_list197);
            predicate_object_pair15=predicate_object_pair(ctx, collector, subject);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulepredicate_object_listEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, predicate_object_pair15.tree);

            // ext/wongi_turtle/Turtle.g:65:44: ( ';' predicate_object_pair[collector, subject] )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) ) 
                {
                case 11:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4) 
                {
            	case 1:
            	    // ext/wongi_turtle/Turtle.g:65:46: ';' predicate_object_pair[collector, subject]
            	    {
            	        char_literal16 = (pANTLR3_COMMON_TOKEN) MATCHT(11, &FOLLOW_11_in_predicate_object_list202); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulepredicate_object_listEx;
            	        }

            	        char_literal16_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal16));
            	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal16_tree);

            	        FOLLOWPUSH(FOLLOW_predicate_object_pair_in_predicate_object_list204);
            	        predicate_object_pair17=predicate_object_pair(ctx, collector, subject);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulepredicate_object_listEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, predicate_object_pair17.tree);

            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulepredicate_object_listEx; /* Prevent compiler warnings */
    rulepredicate_object_listEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end predicate_object_list */

/** 
 * $ANTLR start predicate_object_pair
 * ext/wongi_turtle/Turtle.g:68:1: predicate_object_pair[VALUE collector, VALUE subject] : verb[collector] object_list[collector, subject, $verb.node] ;
 */
static TurtleParser_predicate_object_pair_return
predicate_object_pair(pTurtleParser ctx, VALUE collector, VALUE subject)
{   
    TurtleParser_predicate_object_pair_return retval;
    ANTLR3_UINT32 predicate_object_pair_StartIndex;
    pANTLR3_BASE_TREE root_0;

    TurtleParser_verb_return verb18;
    #undef	RETURN_TYPE_verb18
    #define	RETURN_TYPE_verb18 TurtleParser_verb_return

    TurtleParser_object_list_return object_list19;
    #undef	RETURN_TYPE_object_list19
    #define	RETURN_TYPE_object_list19 TurtleParser_object_list_return


    /* Initialize rule variables
     */
    predicate_object_pair_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(8)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    verb18.tree = NULL;

    object_list19.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        // ext/wongi_turtle/Turtle.g:69:2: ( verb[collector] object_list[collector, subject, $verb.node] )
        // ext/wongi_turtle/Turtle.g:70:2: verb[collector] object_list[collector, subject, $verb.node]
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_verb_in_predicate_object_pair221);
            verb18=verb(ctx, collector);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulepredicate_object_pairEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, verb18.tree);
            FOLLOWPUSH(FOLLOW_object_list_in_predicate_object_pair224);
            object_list19=object_list(ctx, collector, subject, verb18.node);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulepredicate_object_pairEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, object_list19.tree);

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulepredicate_object_pairEx; /* Prevent compiler warnings */
    rulepredicate_object_pairEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end predicate_object_pair */

/** 
 * $ANTLR start object_list
 * ext/wongi_turtle/Turtle.g:73:1: object_list[VALUE collector, VALUE subject, VALUE predicate] : first= object[collector] ( ',' subseq= object[collector] )* ;
 */
static TurtleParser_object_list_return
object_list(pTurtleParser ctx, VALUE collector, VALUE subject, VALUE predicate)
{   
    TurtleParser_object_list_return retval;
    ANTLR3_UINT32 object_list_StartIndex;
    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal20;
    TurtleParser_object_return first;
    #undef	RETURN_TYPE_first
    #define	RETURN_TYPE_first TurtleParser_object_return

    TurtleParser_object_return subseq;
    #undef	RETURN_TYPE_subseq
    #define	RETURN_TYPE_subseq TurtleParser_object_return

    pANTLR3_BASE_TREE char_literal20_tree;

    /* Initialize rule variables
     */
    object_list_StartIndex = INDEX();


    root_0 = NULL;

     VALUE rbDocument = COLLECTOR_DOCUMENT; 
    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(9)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    char_literal20       = NULL;
    first.tree = NULL;

    subseq.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    char_literal20_tree   = NULL;


    retval.tree  = NULL;
    {
        // ext/wongi_turtle/Turtle.g:75:2: (first= object[collector] ( ',' subseq= object[collector] )* )
        // ext/wongi_turtle/Turtle.g:76:2: first= object[collector] ( ',' subseq= object[collector] )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_object_in_object_list246);
            first=object(ctx, collector);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleobject_listEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, first.tree);
            {

                		VALUE argv[] = { subject, predicate, first.node };
                		VALUE statement = rb_class_new_instance( 3, argv, rb_path2class("Wongi::RDF::Statement") );
                		rb_funcall( rbDocument, rb_intern("<<"), 1, statement );
                	
            }

            // ext/wongi_turtle/Turtle.g:81:2: ( ',' subseq= object[collector] )*

            for (;;)
            {
                int alt5=2;
                switch ( LA(1) ) 
                {
                case 12:
                	{
                		alt5=1;
                	}
                    break;

                }

                switch (alt5) 
                {
            	case 1:
            	    // ext/wongi_turtle/Turtle.g:81:3: ',' subseq= object[collector]
            	    {
            	        char_literal20 = (pANTLR3_COMMON_TOKEN) MATCHT(12, &FOLLOW_12_in_object_list253); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleobject_listEx;
            	        }

            	        char_literal20_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal20));
            	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal20_tree);

            	        FOLLOWPUSH(FOLLOW_object_in_object_list257);
            	        subseq=object(ctx, collector);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleobject_listEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, subseq.tree);
            	        {

            	            		VALUE argv[] = { subject, predicate, subseq.node };
            	            		VALUE statement = rb_class_new_instance( 3, argv, rb_path2class("Wongi::RDF::Statement") );
            	            		rb_funcall( rbDocument, rb_intern("<<"), 1, statement );
            	            	
            	        }

            	    }
            	    break;

            	default:
            	    goto loop5;	/* break out of the loop */
            	    break;
                }
            }
            loop5: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleobject_listEx; /* Prevent compiler warnings */
    ruleobject_listEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end object_list */

/** 
 * $ANTLR start subject
 * ext/wongi_turtle/Turtle.g:88:1: subject[VALUE collector] returns [VALUE node] : resource[collector] ;
 */
static TurtleParser_subject_return
subject(pTurtleParser ctx, VALUE collector)
{   
    TurtleParser_subject_return retval;
    ANTLR3_UINT32 subject_StartIndex;
    pANTLR3_BASE_TREE root_0;

    TurtleParser_resource_return resource21;
    #undef	RETURN_TYPE_resource21
    #define	RETURN_TYPE_resource21 TurtleParser_resource_return


    /* Initialize rule variables
     */
    subject_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(10)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    resource21.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        // ext/wongi_turtle/Turtle.g:89:2: ( resource[collector] )
        // ext/wongi_turtle/Turtle.g:90:2: resource[collector]
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_resource_in_subject280);
            resource21=resource(ctx, collector);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesubjectEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, resource21.tree);
            {
                 retval.node= resource21.node; 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesubjectEx; /* Prevent compiler warnings */
    rulesubjectEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end subject */

/** 
 * $ANTLR start verb
 * ext/wongi_turtle/Turtle.g:93:1: verb[VALUE collector] returns [VALUE node] : ( predicate[collector] | 'a' );
 */
static TurtleParser_verb_return
verb(pTurtleParser ctx, VALUE collector)
{   
    TurtleParser_verb_return retval;
    ANTLR3_UINT32 verb_StartIndex;
    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal23;
    TurtleParser_predicate_return predicate22;
    #undef	RETURN_TYPE_predicate22
    #define	RETURN_TYPE_predicate22 TurtleParser_predicate_return

    pANTLR3_BASE_TREE char_literal23_tree;

    /* Initialize rule variables
     */
    verb_StartIndex = INDEX();


    root_0 = NULL;

     retval.node= Qnil; 
    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(11)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    char_literal23       = NULL;
    predicate22.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    char_literal23_tree   = NULL;


    retval.tree  = NULL;
    {
        {
            //  ext/wongi_turtle/Turtle.g:95:2: ( predicate[collector] | 'a' )
            
            ANTLR3_UINT32 alt6;

            alt6=2;

            switch ( LA(1) ) 
            {
            case IDENT:
            case URI:
            	{
            		alt6=1;
            	}
                break;
            case 13:
            	{
            		alt6=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 6;
                EXCEPTION->state        = 0;


                goto ruleverbEx;
            }

            switch (alt6) 
            {
        	case 1:
        	    // ext/wongi_turtle/Turtle.g:96:2: predicate[collector]
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_predicate_in_verb306);
        	        predicate22=predicate(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleverbEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, predicate22.tree);
        	        {
        	             retval.node= predicate22.node; 
        	        }

        	    }
        	    break;
        	case 2:
        	    // ext/wongi_turtle/Turtle.g:98:2: 'a'
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        char_literal23 = (pANTLR3_COMMON_TOKEN) MATCHT(13, &FOLLOW_13_in_verb315); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleverbEx;
        	        }

        	        char_literal23_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal23));
        	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal23_tree);

        	        {

        	            		VALUE rbDocument = COLLECTOR_DOCUMENT;
        	            		rb_funcall( rbDocument, rb_intern("register"), 2, rb_str_new2("rdf"), rb_str_new2(RDF_NS) );
        	            		retval.node= rb_funcall( rbDocument, rb_intern("resource"), 1, rb_str_new2(RDF_TYPE) );
        	            	
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleverbEx; /* Prevent compiler warnings */
    ruleverbEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end verb */

/** 
 * $ANTLR start predicate
 * ext/wongi_turtle/Turtle.g:105:1: predicate[VALUE collector] returns [VALUE node] : resource[collector] ;
 */
static TurtleParser_predicate_return
predicate(pTurtleParser ctx, VALUE collector)
{   
    TurtleParser_predicate_return retval;
    ANTLR3_UINT32 predicate_StartIndex;
    pANTLR3_BASE_TREE root_0;

    TurtleParser_resource_return resource24;
    #undef	RETURN_TYPE_resource24
    #define	RETURN_TYPE_resource24 TurtleParser_resource_return


    /* Initialize rule variables
     */
    predicate_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(12)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    resource24.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        // ext/wongi_turtle/Turtle.g:106:2: ( resource[collector] )
        // ext/wongi_turtle/Turtle.g:107:2: resource[collector]
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_resource_in_predicate334);
            resource24=resource(ctx, collector);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulepredicateEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, resource24.tree);
            {
                 retval.node= resource24.node; 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulepredicateEx; /* Prevent compiler warnings */
    rulepredicateEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end predicate */

/** 
 * $ANTLR start object
 * ext/wongi_turtle/Turtle.g:110:1: object[VALUE collector] returns [VALUE node] : ( resource[collector] | blank[collector] );
 */
static TurtleParser_object_return
object(pTurtleParser ctx, VALUE collector)
{   
    TurtleParser_object_return retval;
    ANTLR3_UINT32 object_StartIndex;
    pANTLR3_BASE_TREE root_0;

    TurtleParser_resource_return resource25;
    #undef	RETURN_TYPE_resource25
    #define	RETURN_TYPE_resource25 TurtleParser_resource_return

    TurtleParser_blank_return blank26;
    #undef	RETURN_TYPE_blank26
    #define	RETURN_TYPE_blank26 TurtleParser_blank_return


    /* Initialize rule variables
     */
    object_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(13)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    resource25.tree = NULL;

    blank26.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        {
            //  ext/wongi_turtle/Turtle.g:111:2: ( resource[collector] | blank[collector] )
            
            ANTLR3_UINT32 alt7;

            alt7=2;

            switch ( LA(1) ) 
            {
            case IDENT:
            case URI:
            	{
            		alt7=1;
            	}
                break;
            case 14:
            	{
            		alt7=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 7;
                EXCEPTION->state        = 0;


                goto ruleobjectEx;
            }

            switch (alt7) 
            {
        	case 1:
        	    // ext/wongi_turtle/Turtle.g:112:2: resource[collector]
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_resource_in_object354);
        	        resource25=resource(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleobjectEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, resource25.tree);
        	        {
        	             retval.node= resource25.node; 
        	        }

        	    }
        	    break;
        	case 2:
        	    // ext/wongi_turtle/Turtle.g:114:2: blank[collector]
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_blank_in_object363);
        	        blank26=blank(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleobjectEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, blank26.tree);
        	        {
        	             retval.node=  blank26.node; 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleobjectEx; /* Prevent compiler warnings */
    ruleobjectEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end object */

/** 
 * $ANTLR start resource
 * ext/wongi_turtle/Turtle.g:117:1: resource[ VALUE collector ] returns [VALUE node] : ( qname[collector] | uri[collector] );
 */
static TurtleParser_resource_return
resource(pTurtleParser ctx, VALUE collector)
{   
    TurtleParser_resource_return retval;
    ANTLR3_UINT32 resource_StartIndex;
    pANTLR3_BASE_TREE root_0;

    TurtleParser_qname_return qname27;
    #undef	RETURN_TYPE_qname27
    #define	RETURN_TYPE_qname27 TurtleParser_qname_return

    TurtleParser_uri_return uri28;
    #undef	RETURN_TYPE_uri28
    #define	RETURN_TYPE_uri28 TurtleParser_uri_return


    /* Initialize rule variables
     */
    resource_StartIndex = INDEX();


    root_0 = NULL;

     VALUE rbDocument = COLLECTOR_DOCUMENT; retval.node= Qnil; 
    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(14)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    qname27.tree = NULL;

    uri28.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        {
            //  ext/wongi_turtle/Turtle.g:119:2: ( qname[collector] | uri[collector] )
            
            ANTLR3_UINT32 alt8;

            alt8=2;

            switch ( LA(1) ) 
            {
            case IDENT:
            	{
            		alt8=1;
            	}
                break;
            case URI:
            	{
            		alt8=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 8;
                EXCEPTION->state        = 0;


                goto ruleresourceEx;
            }

            switch (alt8) 
            {
        	case 1:
        	    // ext/wongi_turtle/Turtle.g:120:2: qname[collector]
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_qname_in_resource388);
        	        qname27=qname(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleresourceEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, qname27.tree);
        	        {
        	             retval.node= rb_funcall( rbDocument, rb_intern("resource"), 1, qname27.ruby_uri ); 
        	        }

        	    }
        	    break;
        	case 2:
        	    // ext/wongi_turtle/Turtle.g:121:4: uri[collector]
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_uri_in_resource396);
        	        uri28=uri(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleresourceEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, uri28.tree);
        	        {
        	             retval.node= rb_funcall( rbDocument, rb_intern("resource"), 1, uri28.ruby_uri ); 
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleresourceEx; /* Prevent compiler warnings */
    ruleresourceEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end resource */

/** 
 * $ANTLR start qname
 * ext/wongi_turtle/Turtle.g:124:1: qname[VALUE collector] returns [VALUE ruby_uri] : prefix= IDENT ':' local= IDENT ;
 */
static TurtleParser_qname_return
qname(pTurtleParser ctx, VALUE collector)
{   
    TurtleParser_qname_return retval;
    ANTLR3_UINT32 qname_StartIndex;
    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    prefix;
    pANTLR3_COMMON_TOKEN    local;
    pANTLR3_COMMON_TOKEN    char_literal29;

    pANTLR3_BASE_TREE prefix_tree;
    pANTLR3_BASE_TREE local_tree;
    pANTLR3_BASE_TREE char_literal29_tree;

    /* Initialize rule variables
     */
    qname_StartIndex = INDEX();


    root_0 = NULL;

     retval.ruby_uri= Qnil; 
    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(15)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    prefix       = NULL;
    local       = NULL;
    char_literal29       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    prefix_tree   = NULL;
    local_tree   = NULL;
    char_literal29_tree   = NULL;


    retval.tree  = NULL;
    {
        // ext/wongi_turtle/Turtle.g:126:2: (prefix= IDENT ':' local= IDENT )
        // ext/wongi_turtle/Turtle.g:127:2: prefix= IDENT ':' local= IDENT
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            prefix = (pANTLR3_COMMON_TOKEN) MATCHT(IDENT, &FOLLOW_IDENT_in_qname424); 
            if  (HASEXCEPTION())
            {
                goto ruleqnameEx;
            }

            prefix_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, prefix));
            ADAPTOR->addChild(ADAPTOR, root_0, prefix_tree);

            char_literal29 = (pANTLR3_COMMON_TOKEN) MATCHT(9, &FOLLOW_9_in_qname426); 
            if  (HASEXCEPTION())
            {
                goto ruleqnameEx;
            }

            char_literal29_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal29));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal29_tree);

            local = (pANTLR3_COMMON_TOKEN) MATCHT(IDENT, &FOLLOW_IDENT_in_qname430); 
            if  (HASEXCEPTION())
            {
                goto ruleqnameEx;
            }

            local_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, local));
            ADAPTOR->addChild(ADAPTOR, root_0, local_tree);

            {

                		VALUE rbDocument = COLLECTOR_DOCUMENT;
                		VALUE prefixURI = rb_funcall( rbDocument, rb_intern("lookup"), 1, rb_str_new2( (prefix->getText(prefix))->chars ) );
                	    VALUE localStr = rb_str_new2( (local->getText(local))->chars );
                	    
                	    //  Ruby URI replaces the whole last segment when it ends with a #
                	    //  but this screws up the entire namespacing.
                	    //  To avoid this, we prepend # to the local part.
                	    if( prefixURI == Qnil ) {
                	        rb_raise( rb_eException, "Unknown prefix %s", (prefix->getText(prefix))->chars );
                	    }
                	    VALUE hash_fragment = rb_funcall( prefixURI, rb_intern("fragment"), 0 );
                	    if( hash_fragment != Qnil ) {
                	      localStr = rb_funcall( rb_str_new2("#"), rb_intern("+"), 1, localStr );
                	    } 
                	    
                	    retval.ruby_uri= rb_funcall( prefixURI, rb_intern("+"), 1, localStr );
                	
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleqnameEx; /* Prevent compiler warnings */
    ruleqnameEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end qname */

/** 
 * $ANTLR start blank
 * ext/wongi_turtle/Turtle.g:148:1: blank[VALUE collector] returns [VALUE node] : '_:' IDENT ;
 */
static TurtleParser_blank_return
blank(pTurtleParser ctx, VALUE collector)
{   
    TurtleParser_blank_return retval;
    ANTLR3_UINT32 blank_StartIndex;
    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    string_literal30;
    pANTLR3_COMMON_TOKEN    IDENT31;

    pANTLR3_BASE_TREE string_literal30_tree;
    pANTLR3_BASE_TREE IDENT31_tree;

    /* Initialize rule variables
     */
    blank_StartIndex = INDEX();


    root_0 = NULL;

     retval.node= Qnil; 
    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(16)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    string_literal30       = NULL;
    IDENT31       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    string_literal30_tree   = NULL;
    IDENT31_tree   = NULL;


    retval.tree  = NULL;
    {
        // ext/wongi_turtle/Turtle.g:150:2: ( '_:' IDENT )
        // ext/wongi_turtle/Turtle.g:151:2: '_:' IDENT
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            string_literal30 = (pANTLR3_COMMON_TOKEN) MATCHT(14, &FOLLOW_14_in_blank456); 
            if  (HASEXCEPTION())
            {
                goto ruleblankEx;
            }

            string_literal30_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, string_literal30));
            ADAPTOR->addChild(ADAPTOR, root_0, string_literal30_tree);

            IDENT31 = (pANTLR3_COMMON_TOKEN) MATCHT(IDENT, &FOLLOW_IDENT_in_blank458); 
            if  (HASEXCEPTION())
            {
                goto ruleblankEx;
            }

            IDENT31_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, IDENT31));
            ADAPTOR->addChild(ADAPTOR, root_0, IDENT31_tree);

            {

                		VALUE id = rb_str_new2( (IDENT31->getText(IDENT31))->chars );
                		retval.node= rb_funcall( collector, rb_intern("import_blank"), 1, id );
                	
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleblankEx; /* Prevent compiler warnings */
    ruleblankEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end blank */

/** 
 * $ANTLR start uri
 * ext/wongi_turtle/Turtle.g:157:1: uri[VALUE collector] returns [VALUE ruby_uri] : URI ;
 */
static TurtleParser_uri_return
uri(pTurtleParser ctx, VALUE collector)
{   
    TurtleParser_uri_return retval;
    ANTLR3_UINT32 uri_StartIndex;
    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    URI32;

    pANTLR3_BASE_TREE URI32_tree;

    /* Initialize rule variables
     */
    uri_StartIndex = INDEX();


    root_0 = NULL;

     retval.ruby_uri= Qnil; 
    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(17)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    URI32       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    URI32_tree   = NULL;


    retval.tree  = NULL;
    {
        // ext/wongi_turtle/Turtle.g:159:2: ( URI )
        // ext/wongi_turtle/Turtle.g:159:4: URI
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            URI32 = (pANTLR3_COMMON_TOKEN) MATCHT(URI, &FOLLOW_URI_in_uri481); 
            if  (HASEXCEPTION())
            {
                goto ruleuriEx;
            }

            URI32_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, URI32));
            ADAPTOR->addChild(ADAPTOR, root_0, URI32_tree);

            {

                		pANTLR3_STRING str = (URI32->getText(URI32)) /*(URI32->getText(URI32))->toUTF8((URI32->getText(URI32)))*/ ;
                		VALUE rb_strUri = rb_str_new2( str->chars );
                		retval.ruby_uri= rb_funcall( rb_path2class("URI"), rb_intern("parse"), 1, rb_strUri );

                		if( ! rb_funcall(retval.ruby_uri, rb_intern("absolute?"), 0) ) {
                			//  relative uri encountered
                			//  document must have a base
                			VALUE rbDocument = COLLECTOR_DOCUMENT;
                			VALUE rbBase = rb_funcall(rbDocument, rb_intern("base"), 0 );
                			if( rbBase == Qnil ) {
                				rb_raise( rb_eException, "Relative URI with no base" );
                			}
                			else {
                				retval.ruby_uri= rb_funcall( rbBase, rb_intern("+"), 1, retval.ruby_uri );
                			}

                		}

                	
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleuriEx; /* Prevent compiler warnings */
    ruleuriEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end uri */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
