/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ext/wongi_turtle/Turtle.g
 *     -                            On : 2012-07-20 14:10:13
 *     -                for the parser : TurtleParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */


	#include <ruby.h>
	#include "extern.h"

	#define COLLECTOR_DOCUMENT   rb_funcall( collector, symDocument, 0 )
	#define MATCH(string)        printf("matched " string "\n");

	#define RDF_NS     "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	#define RDF_TYPE   RDF_NS   "type"
	#define RDF_FIRST  RDF_NS   "first"
	#define RDF_REST   RDF_NS   "rest"
	#define RDF_NIL    RDF_NS   "nil"


/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "TurtleParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pTurtleParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pTurtleParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pTurtleParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pTurtleParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   TurtleParserTokenNames[16+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "BLANK",
        (pANTLR3_UINT8) "IDENT",
        (pANTLR3_UINT8) "PREFIX",
        (pANTLR3_UINT8) "QNAME",
        (pANTLR3_UINT8) "URI",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "','",
        (pANTLR3_UINT8) "'.'",
        (pANTLR3_UINT8) "';'",
        (pANTLR3_UINT8) "'@base'",
        (pANTLR3_UINT8) "'@prefix'",
        (pANTLR3_UINT8) "'['",
        (pANTLR3_UINT8) "']'",
        (pANTLR3_UINT8) "'a'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 TurtleParser_document_return
	document    (pTurtleParser ctx, VALUE collector);
static 
 TurtleParser_statement_return
	statement    (pTurtleParser ctx, VALUE collector);
static 
 TurtleParser_directive_return
	directive    (pTurtleParser ctx, VALUE collector);
static 
 TurtleParser_namespace_declaration_return
	namespace_declaration    (pTurtleParser ctx, VALUE collector);
static 
 TurtleParser_base_declaration_return
	base_declaration    (pTurtleParser ctx, VALUE collector);
static 
 TurtleParser_triples_return
	triples    (pTurtleParser ctx, VALUE collector);
static 
 TurtleParser_predicate_object_list_return
	predicate_object_list    (pTurtleParser ctx, VALUE collector, VALUE subject);
static 
 TurtleParser_predicate_object_pair_return
	predicate_object_pair    (pTurtleParser ctx, VALUE collector, VALUE subject);
static 
 TurtleParser_object_list_return
	object_list    (pTurtleParser ctx, VALUE collector, VALUE subject, VALUE predicate);
static 
 TurtleParser_subject_return
	subject    (pTurtleParser ctx, VALUE collector);
static 
 TurtleParser_verb_return
	verb    (pTurtleParser ctx, VALUE collector);
static 
 TurtleParser_predicate_return
	predicate    (pTurtleParser ctx, VALUE collector);
static 
 TurtleParser_object_return
	object    (pTurtleParser ctx, VALUE collector);
static 
 TurtleParser_resource_return
	resource    (pTurtleParser ctx, VALUE collector);
static 
 TurtleParser_qname_return
	qname    (pTurtleParser ctx, VALUE collector);
static 
 TurtleParser_blank_return
	blank    (pTurtleParser ctx, VALUE collector);
static 
 TurtleParser_collection_return
	collection    (pTurtleParser ctx, VALUE collector);
static 
 TurtleParser_uri_return
	uri    (pTurtleParser ctx, VALUE collector);
static void	TurtleParserFree(pTurtleParser ctx);
static void     TurtleParserReset (pTurtleParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "ext/wongi_turtle/Turtle.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new TurtleParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pTurtleParser
TurtleParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return TurtleParserNewSSD(instream, NULL);
}

/** \brief Create a new TurtleParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pTurtleParser
TurtleParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pTurtleParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pTurtleParser) ANTLR3_CALLOC(1, sizeof(TurtleParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in TurtleParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our TurtleParser interface
     */
    ctx->document	= document;
    ctx->statement	= statement;
    ctx->directive	= directive;
    ctx->namespace_declaration	= namespace_declaration;
    ctx->base_declaration	= base_declaration;
    ctx->triples	= triples;
    ctx->predicate_object_list	= predicate_object_list;
    ctx->predicate_object_pair	= predicate_object_pair;
    ctx->object_list	= object_list;
    ctx->subject	= subject;
    ctx->verb	= verb;
    ctx->predicate	= predicate;
    ctx->object	= object;
    ctx->resource	= resource;
    ctx->qname	= qname;
    ctx->blank	= blank;
    ctx->collection	= collection;
    ctx->uri	= uri;
    ctx->free			= TurtleParserFree;
    ctx->reset			= TurtleParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);

ctx->vectors	= antlr3VectorFactoryNew(0);
    /* Install the token table
     */
    PSRSTATE->tokenNames   = TurtleParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
TurtleParserReset (pTurtleParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 TurtleParserFree(pTurtleParser ctx)
 {
    /* Free any scope memory
     */

ctx->vectors->close(ctx->vectors);
/* We created the adaptor so we must free it
 */
ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return TurtleParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_statement_in_document82  */
static	ANTLR3_BITWORD FOLLOW_statement_in_document82_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000018182) };
static  ANTLR3_BITSET_LIST FOLLOW_statement_in_document82	= { FOLLOW_statement_in_document82_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_directive_in_statement97  */
static	ANTLR3_BITWORD FOLLOW_directive_in_statement97_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002000) };
static  ANTLR3_BITSET_LIST FOLLOW_directive_in_statement97	= { FOLLOW_directive_in_statement97_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_triples_in_statement102  */
static	ANTLR3_BITWORD FOLLOW_triples_in_statement102_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002000) };
static  ANTLR3_BITSET_LIST FOLLOW_triples_in_statement102	= { FOLLOW_triples_in_statement102_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_13_in_statement107  */
static	ANTLR3_BITWORD FOLLOW_13_in_statement107_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_13_in_statement107	= { FOLLOW_13_in_statement107_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_namespace_declaration_in_directive118  */
static	ANTLR3_BITWORD FOLLOW_namespace_declaration_in_directive118_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_namespace_declaration_in_directive118	= { FOLLOW_namespace_declaration_in_directive118_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_base_declaration_in_directive124  */
static	ANTLR3_BITWORD FOLLOW_base_declaration_in_directive124_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_base_declaration_in_directive124	= { FOLLOW_base_declaration_in_directive124_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_namespace_declaration138  */
static	ANTLR3_BITWORD FOLLOW_16_in_namespace_declaration138_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_namespace_declaration138	= { FOLLOW_16_in_namespace_declaration138_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PREFIX_in_namespace_declaration140  */
static	ANTLR3_BITWORD FOLLOW_PREFIX_in_namespace_declaration140_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_PREFIX_in_namespace_declaration140	= { FOLLOW_PREFIX_in_namespace_declaration140_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_uri_in_namespace_declaration142  */
static	ANTLR3_BITWORD FOLLOW_uri_in_namespace_declaration142_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_uri_in_namespace_declaration142	= { FOLLOW_uri_in_namespace_declaration142_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_base_declaration159  */
static	ANTLR3_BITWORD FOLLOW_15_in_base_declaration159_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_base_declaration159	= { FOLLOW_15_in_base_declaration159_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_uri_in_base_declaration161  */
static	ANTLR3_BITWORD FOLLOW_uri_in_base_declaration161_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_uri_in_base_declaration161	= { FOLLOW_uri_in_base_declaration161_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_subject_in_triples178  */
static	ANTLR3_BITWORD FOLLOW_subject_in_triples178_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080180) };
static  ANTLR3_BITSET_LIST FOLLOW_subject_in_triples178	= { FOLLOW_subject_in_triples178_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_object_list_in_triples181  */
static	ANTLR3_BITWORD FOLLOW_predicate_object_list_in_triples181_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_object_list_in_triples181	= { FOLLOW_predicate_object_list_in_triples181_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_object_pair_in_predicate_object_list195  */
static	ANTLR3_BITWORD FOLLOW_predicate_object_pair_in_predicate_object_list195_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004002) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_object_pair_in_predicate_object_list195	= { FOLLOW_predicate_object_pair_in_predicate_object_list195_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_14_in_predicate_object_list200  */
static	ANTLR3_BITWORD FOLLOW_14_in_predicate_object_list200_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080180) };
static  ANTLR3_BITSET_LIST FOLLOW_14_in_predicate_object_list200	= { FOLLOW_14_in_predicate_object_list200_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_object_pair_in_predicate_object_list202  */
static	ANTLR3_BITWORD FOLLOW_predicate_object_pair_in_predicate_object_list202_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004002) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_object_pair_in_predicate_object_list202	= { FOLLOW_predicate_object_pair_in_predicate_object_list202_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_verb_in_predicate_object_pair219  */
static	ANTLR3_BITWORD FOLLOW_verb_in_predicate_object_pair219_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020590) };
static  ANTLR3_BITSET_LIST FOLLOW_verb_in_predicate_object_pair219	= { FOLLOW_verb_in_predicate_object_pair219_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_object_list_in_predicate_object_pair222  */
static	ANTLR3_BITWORD FOLLOW_object_list_in_predicate_object_pair222_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_object_list_in_predicate_object_pair222	= { FOLLOW_object_list_in_predicate_object_pair222_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_object_in_object_list244  */
static	ANTLR3_BITWORD FOLLOW_object_in_object_list244_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001002) };
static  ANTLR3_BITSET_LIST FOLLOW_object_in_object_list244	= { FOLLOW_object_in_object_list244_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_12_in_object_list251  */
static	ANTLR3_BITWORD FOLLOW_12_in_object_list251_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020590) };
static  ANTLR3_BITSET_LIST FOLLOW_12_in_object_list251	= { FOLLOW_12_in_object_list251_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_object_in_object_list255  */
static	ANTLR3_BITWORD FOLLOW_object_in_object_list255_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001002) };
static  ANTLR3_BITSET_LIST FOLLOW_object_in_object_list255	= { FOLLOW_object_in_object_list255_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_resource_in_subject278  */
static	ANTLR3_BITWORD FOLLOW_resource_in_subject278_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_resource_in_subject278	= { FOLLOW_resource_in_subject278_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_in_verb304  */
static	ANTLR3_BITWORD FOLLOW_predicate_in_verb304_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_in_verb304	= { FOLLOW_predicate_in_verb304_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_verb313  */
static	ANTLR3_BITWORD FOLLOW_19_in_verb313_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_verb313	= { FOLLOW_19_in_verb313_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_resource_in_predicate332  */
static	ANTLR3_BITWORD FOLLOW_resource_in_predicate332_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_resource_in_predicate332	= { FOLLOW_resource_in_predicate332_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_resource_in_object352  */
static	ANTLR3_BITWORD FOLLOW_resource_in_object352_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_resource_in_object352	= { FOLLOW_resource_in_object352_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_blank_in_object361  */
static	ANTLR3_BITWORD FOLLOW_blank_in_object361_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_blank_in_object361	= { FOLLOW_blank_in_object361_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_qname_in_resource386  */
static	ANTLR3_BITWORD FOLLOW_qname_in_resource386_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_qname_in_resource386	= { FOLLOW_qname_in_resource386_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_uri_in_resource394  */
static	ANTLR3_BITWORD FOLLOW_uri_in_resource394_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_uri_in_resource394	= { FOLLOW_uri_in_resource394_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_QNAME_in_qname422  */
static	ANTLR3_BITWORD FOLLOW_QNAME_in_qname422_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_QNAME_in_qname422	= { FOLLOW_QNAME_in_qname422_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_BLANK_in_blank448  */
static	ANTLR3_BITWORD FOLLOW_BLANK_in_blank448_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_BLANK_in_blank448	= { FOLLOW_BLANK_in_blank448_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_blank461  */
static	ANTLR3_BITWORD FOLLOW_17_in_blank461_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000C0180) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_blank461	= { FOLLOW_17_in_blank461_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_object_list_in_blank463  */
static	ANTLR3_BITWORD FOLLOW_predicate_object_list_in_blank463_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000040000) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_object_list_in_blank463	= { FOLLOW_predicate_object_list_in_blank463_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_blank467  */
static	ANTLR3_BITWORD FOLLOW_18_in_blank467_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_blank467	= { FOLLOW_18_in_blank467_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_10_in_blank474  */
static	ANTLR3_BITWORD FOLLOW_10_in_blank474_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020D90) };
static  ANTLR3_BITSET_LIST FOLLOW_10_in_blank474	= { FOLLOW_10_in_blank474_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_collection_in_blank476  */
static	ANTLR3_BITWORD FOLLOW_collection_in_blank476_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_collection_in_blank476	= { FOLLOW_collection_in_blank476_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_11_in_blank479  */
static	ANTLR3_BITWORD FOLLOW_11_in_blank479_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_11_in_blank479	= { FOLLOW_11_in_blank479_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_object_in_collection514  */
static	ANTLR3_BITWORD FOLLOW_object_in_collection514_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020590) };
static  ANTLR3_BITSET_LIST FOLLOW_object_in_collection514	= { FOLLOW_object_in_collection514_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_collection_in_collection525  */
static	ANTLR3_BITWORD FOLLOW_collection_in_collection525_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_collection_in_collection525	= { FOLLOW_collection_in_collection525_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_URI_in_uri551  */
static	ANTLR3_BITWORD FOLLOW_URI_in_uri551_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_URI_in_uri551	= { FOLLOW_URI_in_uri551_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start document
 * ext/wongi_turtle/Turtle.g:30:1: document[VALUE collector] : ( statement[collector] )* ;
 */
static TurtleParser_document_return
document(pTurtleParser ctx, VALUE collector)
{
    TurtleParser_document_return retval;

    ANTLR3_UINT32 document_StartIndex;

    pANTLR3_BASE_TREE root_0;

    TurtleParser_statement_return statement1;
    #undef	RETURN_TYPE_statement1
    #define	RETURN_TYPE_statement1 TurtleParser_statement_return


    /* Initialize rule variables
     */
    document_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(1)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    statement1.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ext/wongi_turtle/Turtle.g:30:27: ( ( statement[collector] )* )
        // ext/wongi_turtle/Turtle.g:30:29: ( statement[collector] )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // ext/wongi_turtle/Turtle.g:30:29: ( statement[collector] )*

            for (;;)
            {
                int alt1=2;
                switch ( LA(1) )
                {
                case QNAME:
                case URI:
                case 15:
                case 16:
                	{
                		alt1=1;
                	}
                    break;

                }

                switch (alt1)
                {
            	case 1:
            	    // ext/wongi_turtle/Turtle.g:30:29: statement[collector]
            	    {
            	        FOLLOWPUSH(FOLLOW_statement_in_document82);
            	        statement1=statement(ctx, collector);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledocumentEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, statement1.tree);

            	    }
            	    break;

            	default:
            	    goto loop1;	/* break out of the loop */
            	    break;
                }
            }
            loop1: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruledocumentEx; /* Prevent compiler warnings */
    ruledocumentEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end document */

/**
 * $ANTLR start statement
 * ext/wongi_turtle/Turtle.g:32:1: statement[VALUE collector] : ( directive[collector] | triples[collector] ) '.' ;
 */
static TurtleParser_statement_return
statement(pTurtleParser ctx, VALUE collector)
{
    TurtleParser_statement_return retval;

    ANTLR3_UINT32 statement_StartIndex;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal4;
    TurtleParser_directive_return directive2;
    #undef	RETURN_TYPE_directive2
    #define	RETURN_TYPE_directive2 TurtleParser_directive_return

    TurtleParser_triples_return triples3;
    #undef	RETURN_TYPE_triples3
    #define	RETURN_TYPE_triples3 TurtleParser_triples_return

    pANTLR3_BASE_TREE char_literal4_tree;

    /* Initialize rule variables
     */
    statement_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(2)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    char_literal4       = NULL;
    directive2.tree = NULL;

    triples3.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal4_tree   = NULL;


    retval.tree  = NULL;

    {
        // ext/wongi_turtle/Turtle.g:32:28: ( ( directive[collector] | triples[collector] ) '.' )
        // ext/wongi_turtle/Turtle.g:32:30: ( directive[collector] | triples[collector] ) '.'
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // ext/wongi_turtle/Turtle.g:32:30: ( directive[collector] | triples[collector] )
            {
                int alt2=2;
                switch ( LA(1) )
                {
                case 15:
                case 16:
                	{
                		alt2=1;
                	}
                    break;
                case QNAME:
                case URI:
                	{
                		alt2=2;
                	}
                    break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 2;
                    EXCEPTION->state        = 0;


                    goto rulestatementEx;

                }

                switch (alt2)
                {
            	case 1:
            	    // ext/wongi_turtle/Turtle.g:32:32: directive[collector]
            	    {
            	        FOLLOWPUSH(FOLLOW_directive_in_statement97);
            	        directive2=directive(ctx, collector);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulestatementEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, directive2.tree);

            	    }
            	    break;
            	case 2:
            	    // ext/wongi_turtle/Turtle.g:32:55: triples[collector]
            	    {
            	        FOLLOWPUSH(FOLLOW_triples_in_statement102);
            	        triples3=triples(ctx, collector);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulestatementEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, triples3.tree);

            	    }
            	    break;

                }
            }

            char_literal4 = (pANTLR3_COMMON_TOKEN) MATCHT(13, &FOLLOW_13_in_statement107);
            if  (HASEXCEPTION())
            {
                goto rulestatementEx;
            }

            char_literal4_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal4));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal4_tree);


        }

    }

    // This is where rules clean up and exit
    //
    goto rulestatementEx; /* Prevent compiler warnings */
    rulestatementEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end statement */

/**
 * $ANTLR start directive
 * ext/wongi_turtle/Turtle.g:34:1: directive[VALUE collector] : ( namespace_declaration[collector] | base_declaration[collector] );
 */
static TurtleParser_directive_return
directive(pTurtleParser ctx, VALUE collector)
{
    TurtleParser_directive_return retval;

    ANTLR3_UINT32 directive_StartIndex;

    pANTLR3_BASE_TREE root_0;

    TurtleParser_namespace_declaration_return namespace_declaration5;
    #undef	RETURN_TYPE_namespace_declaration5
    #define	RETURN_TYPE_namespace_declaration5 TurtleParser_namespace_declaration_return

    TurtleParser_base_declaration_return base_declaration6;
    #undef	RETURN_TYPE_base_declaration6
    #define	RETURN_TYPE_base_declaration6 TurtleParser_base_declaration_return


    /* Initialize rule variables
     */
    directive_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(3)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    namespace_declaration5.tree = NULL;

    base_declaration6.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        {
            //  ext/wongi_turtle/Turtle.g:35:2: ( namespace_declaration[collector] | base_declaration[collector] )

            ANTLR3_UINT32 alt3;

            alt3=2;

            switch ( LA(1) )
            {
            case 16:
            	{
            		alt3=1;
            	}
                break;
            case 15:
            	{
            		alt3=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 3;
                EXCEPTION->state        = 0;


                goto ruledirectiveEx;

            }

            switch (alt3)
            {
        	case 1:
        	    // ext/wongi_turtle/Turtle.g:35:4: namespace_declaration[collector]
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_namespace_declaration_in_directive118);
        	        namespace_declaration5=namespace_declaration(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledirectiveEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, namespace_declaration5.tree);

        	    }
        	    break;
        	case 2:
        	    // ext/wongi_turtle/Turtle.g:36:4: base_declaration[collector]
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_base_declaration_in_directive124);
        	        base_declaration6=base_declaration(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledirectiveEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, base_declaration6.tree);

        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruledirectiveEx; /* Prevent compiler warnings */
    ruledirectiveEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end directive */

/**
 * $ANTLR start namespace_declaration
 * ext/wongi_turtle/Turtle.g:39:1: namespace_declaration[VALUE collector] : '@prefix' PREFIX uri[collector] ;
 */
static TurtleParser_namespace_declaration_return
namespace_declaration(pTurtleParser ctx, VALUE collector)
{
    TurtleParser_namespace_declaration_return retval;

    ANTLR3_UINT32 namespace_declaration_StartIndex;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    string_literal7;
    pANTLR3_COMMON_TOKEN    PREFIX8;
    TurtleParser_uri_return uri9;
    #undef	RETURN_TYPE_uri9
    #define	RETURN_TYPE_uri9 TurtleParser_uri_return

    pANTLR3_BASE_TREE string_literal7_tree;
    pANTLR3_BASE_TREE PREFIX8_tree;

    /* Initialize rule variables
     */
    namespace_declaration_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(4)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    string_literal7       = NULL;
    PREFIX8       = NULL;
    uri9.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    string_literal7_tree   = NULL;
    PREFIX8_tree   = NULL;


    retval.tree  = NULL;

    {
        // ext/wongi_turtle/Turtle.g:40:2: ( '@prefix' PREFIX uri[collector] )
        // ext/wongi_turtle/Turtle.g:41:2: '@prefix' PREFIX uri[collector]
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            string_literal7 = (pANTLR3_COMMON_TOKEN) MATCHT(16, &FOLLOW_16_in_namespace_declaration138);
            if  (HASEXCEPTION())
            {
                goto rulenamespace_declarationEx;
            }

            string_literal7_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, string_literal7));
            ADAPTOR->addChild(ADAPTOR, root_0, string_literal7_tree);


            PREFIX8 = (pANTLR3_COMMON_TOKEN) MATCHT(PREFIX, &FOLLOW_PREFIX_in_namespace_declaration140);
            if  (HASEXCEPTION())
            {
                goto rulenamespace_declarationEx;
            }

            PREFIX8_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, PREFIX8));
            ADAPTOR->addChild(ADAPTOR, root_0, PREFIX8_tree);


            FOLLOWPUSH(FOLLOW_uri_in_namespace_declaration142);
            uri9=uri(ctx, collector);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulenamespace_declarationEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, uri9.tree);

            {

                		VALUE rbPrefix = rb_str_new2( (PREFIX8->getText(PREFIX8))->chars );
                		VALUE rbFull = 
                uri9.ruby_uri
                ;

                		rb_funcall( collector, symRegister, 2, rbPrefix, rbFull );
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulenamespace_declarationEx; /* Prevent compiler warnings */
    rulenamespace_declarationEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end namespace_declaration */

/**
 * $ANTLR start base_declaration
 * ext/wongi_turtle/Turtle.g:50:1: base_declaration[VALUE collector] : '@base' uri[collector] ;
 */
static TurtleParser_base_declaration_return
base_declaration(pTurtleParser ctx, VALUE collector)
{
    TurtleParser_base_declaration_return retval;

    ANTLR3_UINT32 base_declaration_StartIndex;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    string_literal10;
    TurtleParser_uri_return uri11;
    #undef	RETURN_TYPE_uri11
    #define	RETURN_TYPE_uri11 TurtleParser_uri_return

    pANTLR3_BASE_TREE string_literal10_tree;

    /* Initialize rule variables
     */
    base_declaration_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(5)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    string_literal10       = NULL;
    uri11.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    string_literal10_tree   = NULL;


    retval.tree  = NULL;

    {
        // ext/wongi_turtle/Turtle.g:51:2: ( '@base' uri[collector] )
        // ext/wongi_turtle/Turtle.g:52:2: '@base' uri[collector]
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            string_literal10 = (pANTLR3_COMMON_TOKEN) MATCHT(15, &FOLLOW_15_in_base_declaration159);
            if  (HASEXCEPTION())
            {
                goto rulebase_declarationEx;
            }

            string_literal10_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, string_literal10));
            ADAPTOR->addChild(ADAPTOR, root_0, string_literal10_tree);


            FOLLOWPUSH(FOLLOW_uri_in_base_declaration161);
            uri11=uri(ctx, collector);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulebase_declarationEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, uri11.tree);

            {

                		VALUE rbDocument = COLLECTOR_DOCUMENT;
                		rb_funcall( rbDocument, symBaseEQ, 1, uri11.ruby_uri
                 );
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulebase_declarationEx; /* Prevent compiler warnings */
    rulebase_declarationEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end base_declaration */

/**
 * $ANTLR start triples
 * ext/wongi_turtle/Turtle.g:59:1: triples[VALUE collector] : subject[collector] predicate_object_list[collector, $subject.node] ;
 */
static TurtleParser_triples_return
triples(pTurtleParser ctx, VALUE collector)
{
    TurtleParser_triples_return retval;

    ANTLR3_UINT32 triples_StartIndex;

    pANTLR3_BASE_TREE root_0;

    TurtleParser_subject_return subject12;
    #undef	RETURN_TYPE_subject12
    #define	RETURN_TYPE_subject12 TurtleParser_subject_return

    TurtleParser_predicate_object_list_return predicate_object_list13;
    #undef	RETURN_TYPE_predicate_object_list13
    #define	RETURN_TYPE_predicate_object_list13 TurtleParser_predicate_object_list_return


    /* Initialize rule variables
     */
    triples_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(6)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    subject12.tree = NULL;

    predicate_object_list13.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ext/wongi_turtle/Turtle.g:60:2: ( subject[collector] predicate_object_list[collector, $subject.node] )
        // ext/wongi_turtle/Turtle.g:61:2: subject[collector] predicate_object_list[collector, $subject.node]
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_subject_in_triples178);
            subject12=subject(ctx, collector);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruletriplesEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, subject12.tree);

            FOLLOWPUSH(FOLLOW_predicate_object_list_in_triples181);
            predicate_object_list13=predicate_object_list(ctx, collector, 
            subject12.node
            );

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruletriplesEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, predicate_object_list13.tree);

        }

    }

    // This is where rules clean up and exit
    //
    goto ruletriplesEx; /* Prevent compiler warnings */
    ruletriplesEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end triples */

/**
 * $ANTLR start predicate_object_list
 * ext/wongi_turtle/Turtle.g:64:1: predicate_object_list[VALUE collector, VALUE subject] : predicate_object_pair[collector, subject] ( ';' predicate_object_pair[collector, subject] )* ;
 */
static TurtleParser_predicate_object_list_return
predicate_object_list(pTurtleParser ctx, VALUE collector, VALUE subject)
{
    TurtleParser_predicate_object_list_return retval;

    ANTLR3_UINT32 predicate_object_list_StartIndex;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal15;
    TurtleParser_predicate_object_pair_return predicate_object_pair14;
    #undef	RETURN_TYPE_predicate_object_pair14
    #define	RETURN_TYPE_predicate_object_pair14 TurtleParser_predicate_object_pair_return

    TurtleParser_predicate_object_pair_return predicate_object_pair16;
    #undef	RETURN_TYPE_predicate_object_pair16
    #define	RETURN_TYPE_predicate_object_pair16 TurtleParser_predicate_object_pair_return

    pANTLR3_BASE_TREE char_literal15_tree;

    /* Initialize rule variables
     */
    predicate_object_list_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(7)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    char_literal15       = NULL;
    predicate_object_pair14.tree = NULL;

    predicate_object_pair16.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal15_tree   = NULL;


    retval.tree  = NULL;

    {
        // ext/wongi_turtle/Turtle.g:65:2: ( predicate_object_pair[collector, subject] ( ';' predicate_object_pair[collector, subject] )* )
        // ext/wongi_turtle/Turtle.g:66:2: predicate_object_pair[collector, subject] ( ';' predicate_object_pair[collector, subject] )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_predicate_object_pair_in_predicate_object_list195);
            predicate_object_pair14=predicate_object_pair(ctx, collector, subject);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulepredicate_object_listEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, predicate_object_pair14.tree);

            // ext/wongi_turtle/Turtle.g:66:44: ( ';' predicate_object_pair[collector, subject] )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) )
                {
                case 14:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4)
                {
            	case 1:
            	    // ext/wongi_turtle/Turtle.g:66:46: ';' predicate_object_pair[collector, subject]
            	    {
            	        char_literal15 = (pANTLR3_COMMON_TOKEN) MATCHT(14, &FOLLOW_14_in_predicate_object_list200);
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulepredicate_object_listEx;
            	        }

            	        char_literal15_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal15));
            	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal15_tree);


            	        FOLLOWPUSH(FOLLOW_predicate_object_pair_in_predicate_object_list202);
            	        predicate_object_pair16=predicate_object_pair(ctx, collector, subject);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulepredicate_object_listEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, predicate_object_pair16.tree);

            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulepredicate_object_listEx; /* Prevent compiler warnings */
    rulepredicate_object_listEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end predicate_object_list */

/**
 * $ANTLR start predicate_object_pair
 * ext/wongi_turtle/Turtle.g:69:1: predicate_object_pair[VALUE collector, VALUE subject] : verb[collector] object_list[collector, subject, $verb.node] ;
 */
static TurtleParser_predicate_object_pair_return
predicate_object_pair(pTurtleParser ctx, VALUE collector, VALUE subject)
{
    TurtleParser_predicate_object_pair_return retval;

    ANTLR3_UINT32 predicate_object_pair_StartIndex;

    pANTLR3_BASE_TREE root_0;

    TurtleParser_verb_return verb17;
    #undef	RETURN_TYPE_verb17
    #define	RETURN_TYPE_verb17 TurtleParser_verb_return

    TurtleParser_object_list_return object_list18;
    #undef	RETURN_TYPE_object_list18
    #define	RETURN_TYPE_object_list18 TurtleParser_object_list_return


    /* Initialize rule variables
     */
    predicate_object_pair_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(8)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    verb17.tree = NULL;

    object_list18.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ext/wongi_turtle/Turtle.g:70:2: ( verb[collector] object_list[collector, subject, $verb.node] )
        // ext/wongi_turtle/Turtle.g:71:2: verb[collector] object_list[collector, subject, $verb.node]
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_verb_in_predicate_object_pair219);
            verb17=verb(ctx, collector);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulepredicate_object_pairEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, verb17.tree);

            FOLLOWPUSH(FOLLOW_object_list_in_predicate_object_pair222);
            object_list18=object_list(ctx, collector, subject, 
            verb17.node
            );

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulepredicate_object_pairEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, object_list18.tree);

        }

    }

    // This is where rules clean up and exit
    //
    goto rulepredicate_object_pairEx; /* Prevent compiler warnings */
    rulepredicate_object_pairEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end predicate_object_pair */

/**
 * $ANTLR start object_list
 * ext/wongi_turtle/Turtle.g:74:1: object_list[VALUE collector, VALUE subject, VALUE predicate] : first= object[collector] ( ',' subseq= object[collector] )* ;
 */
static TurtleParser_object_list_return
object_list(pTurtleParser ctx, VALUE collector, VALUE subject, VALUE predicate)
{
    TurtleParser_object_list_return retval;

    ANTLR3_UINT32 object_list_StartIndex;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal19;
    TurtleParser_object_return first;
    #undef	RETURN_TYPE_first
    #define	RETURN_TYPE_first TurtleParser_object_return

    TurtleParser_object_return subseq;
    #undef	RETURN_TYPE_subseq
    #define	RETURN_TYPE_subseq TurtleParser_object_return

    pANTLR3_BASE_TREE char_literal19_tree;

    /* Initialize rule variables
     */
    object_list_StartIndex = INDEX();


    root_0 = NULL;

     VALUE rbDocument = COLLECTOR_DOCUMENT; 
    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(9)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    char_literal19       = NULL;
    first.tree = NULL;

    subseq.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal19_tree   = NULL;


    retval.tree  = NULL;

    {
        // ext/wongi_turtle/Turtle.g:76:2: (first= object[collector] ( ',' subseq= object[collector] )* )
        // ext/wongi_turtle/Turtle.g:77:2: first= object[collector] ( ',' subseq= object[collector] )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_object_in_object_list244);
            first=object(ctx, collector);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleobject_listEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, first.tree);

            {

                		VALUE argv[] = { subject, predicate, 
                first.node
                 };
                		VALUE statement = rb_class_new_instance( 3, argv, cStatement );
                		rb_funcall( rbDocument, symLSHIFT, 1, statement );
                	
            }


            // ext/wongi_turtle/Turtle.g:82:2: ( ',' subseq= object[collector] )*

            for (;;)
            {
                int alt5=2;
                switch ( LA(1) )
                {
                case 12:
                	{
                		alt5=1;
                	}
                    break;

                }

                switch (alt5)
                {
            	case 1:
            	    // ext/wongi_turtle/Turtle.g:82:3: ',' subseq= object[collector]
            	    {
            	        char_literal19 = (pANTLR3_COMMON_TOKEN) MATCHT(12, &FOLLOW_12_in_object_list251);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleobject_listEx;
            	        }

            	        char_literal19_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal19));
            	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal19_tree);


            	        FOLLOWPUSH(FOLLOW_object_in_object_list255);
            	        subseq=object(ctx, collector);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleobject_listEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, subseq.tree);

            	        {

            	            		VALUE argv[] = { subject, predicate, 
            	            subseq.node
            	             };
            	            		VALUE statement = rb_class_new_instance( 3, argv, cStatement );
            	            		rb_funcall( rbDocument, symLSHIFT, 1, statement );
            	            	
            	        }


            	    }
            	    break;

            	default:
            	    goto loop5;	/* break out of the loop */
            	    break;
                }
            }
            loop5: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleobject_listEx; /* Prevent compiler warnings */
    ruleobject_listEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end object_list */

/**
 * $ANTLR start subject
 * ext/wongi_turtle/Turtle.g:89:1: subject[VALUE collector] returns [VALUE node] : resource[collector] ;
 */
static TurtleParser_subject_return
subject(pTurtleParser ctx, VALUE collector)
{
    TurtleParser_subject_return retval;

    ANTLR3_UINT32 subject_StartIndex;

    pANTLR3_BASE_TREE root_0;

    TurtleParser_resource_return resource20;
    #undef	RETURN_TYPE_resource20
    #define	RETURN_TYPE_resource20 TurtleParser_resource_return


    /* Initialize rule variables
     */
    subject_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(10)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    resource20.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ext/wongi_turtle/Turtle.g:90:2: ( resource[collector] )
        // ext/wongi_turtle/Turtle.g:91:2: resource[collector]
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_resource_in_subject278);
            resource20=resource(ctx, collector);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesubjectEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, resource20.tree);

            {
                 retval.node= 
                resource20.node
                ;
                 
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulesubjectEx; /* Prevent compiler warnings */
    rulesubjectEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end subject */

/**
 * $ANTLR start verb
 * ext/wongi_turtle/Turtle.g:94:1: verb[VALUE collector] returns [VALUE node] : ( predicate[collector] | 'a' );
 */
static TurtleParser_verb_return
verb(pTurtleParser ctx, VALUE collector)
{
    TurtleParser_verb_return retval;

    ANTLR3_UINT32 verb_StartIndex;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal22;
    TurtleParser_predicate_return predicate21;
    #undef	RETURN_TYPE_predicate21
    #define	RETURN_TYPE_predicate21 TurtleParser_predicate_return

    pANTLR3_BASE_TREE char_literal22_tree;

    /* Initialize rule variables
     */
    verb_StartIndex = INDEX();


    root_0 = NULL;

     retval.node= Qnil;
     
    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(11)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    char_literal22       = NULL;
    predicate21.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal22_tree   = NULL;


    retval.tree  = NULL;

    {
        {
            //  ext/wongi_turtle/Turtle.g:96:2: ( predicate[collector] | 'a' )

            ANTLR3_UINT32 alt6;

            alt6=2;

            switch ( LA(1) )
            {
            case QNAME:
            case URI:
            	{
            		alt6=1;
            	}
                break;
            case 19:
            	{
            		alt6=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 6;
                EXCEPTION->state        = 0;


                goto ruleverbEx;

            }

            switch (alt6)
            {
        	case 1:
        	    // ext/wongi_turtle/Turtle.g:97:2: predicate[collector]
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_predicate_in_verb304);
        	        predicate21=predicate(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleverbEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, predicate21.tree);

        	        {
        	             retval.node= 
        	            predicate21.node
        	            ;
        	             
        	        }


        	    }
        	    break;
        	case 2:
        	    // ext/wongi_turtle/Turtle.g:99:2: 'a'
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        char_literal22 = (pANTLR3_COMMON_TOKEN) MATCHT(19, &FOLLOW_19_in_verb313);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleverbEx;
        	        }

        	        char_literal22_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal22));
        	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal22_tree);


        	        {

        	            		VALUE rbDocument = COLLECTOR_DOCUMENT;
        	            		rb_funcall( rbDocument, symCommonEXCL, 0 );
        	            		retval.node= rb_funcall( rbDocument, symResource, 1, rb_str_new2(RDF_TYPE) );

        	            	
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleverbEx; /* Prevent compiler warnings */
    ruleverbEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end verb */

/**
 * $ANTLR start predicate
 * ext/wongi_turtle/Turtle.g:106:1: predicate[VALUE collector] returns [VALUE node] : resource[collector] ;
 */
static TurtleParser_predicate_return
predicate(pTurtleParser ctx, VALUE collector)
{
    TurtleParser_predicate_return retval;

    ANTLR3_UINT32 predicate_StartIndex;

    pANTLR3_BASE_TREE root_0;

    TurtleParser_resource_return resource23;
    #undef	RETURN_TYPE_resource23
    #define	RETURN_TYPE_resource23 TurtleParser_resource_return


    /* Initialize rule variables
     */
    predicate_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(12)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    resource23.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ext/wongi_turtle/Turtle.g:107:2: ( resource[collector] )
        // ext/wongi_turtle/Turtle.g:108:2: resource[collector]
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_resource_in_predicate332);
            resource23=resource(ctx, collector);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulepredicateEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, resource23.tree);

            {
                 retval.node= 
                resource23.node
                ;
                 
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulepredicateEx; /* Prevent compiler warnings */
    rulepredicateEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end predicate */

/**
 * $ANTLR start object
 * ext/wongi_turtle/Turtle.g:111:1: object[VALUE collector] returns [VALUE node] : ( resource[collector] | blank[collector] );
 */
static TurtleParser_object_return
object(pTurtleParser ctx, VALUE collector)
{
    TurtleParser_object_return retval;

    ANTLR3_UINT32 object_StartIndex;

    pANTLR3_BASE_TREE root_0;

    TurtleParser_resource_return resource24;
    #undef	RETURN_TYPE_resource24
    #define	RETURN_TYPE_resource24 TurtleParser_resource_return

    TurtleParser_blank_return blank25;
    #undef	RETURN_TYPE_blank25
    #define	RETURN_TYPE_blank25 TurtleParser_blank_return


    /* Initialize rule variables
     */
    object_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(13)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    resource24.tree = NULL;

    blank25.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        {
            //  ext/wongi_turtle/Turtle.g:112:2: ( resource[collector] | blank[collector] )

            ANTLR3_UINT32 alt7;

            alt7=2;

            switch ( LA(1) )
            {
            case QNAME:
            case URI:
            	{
            		alt7=1;
            	}
                break;
            case BLANK:
            case 10:
            case 17:
            	{
            		alt7=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 7;
                EXCEPTION->state        = 0;


                goto ruleobjectEx;

            }

            switch (alt7)
            {
        	case 1:
        	    // ext/wongi_turtle/Turtle.g:113:2: resource[collector]
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_resource_in_object352);
        	        resource24=resource(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleobjectEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, resource24.tree);

        	        {
        	             retval.node= 
        	            resource24.node
        	            ;
        	             
        	        }


        	    }
        	    break;
        	case 2:
        	    // ext/wongi_turtle/Turtle.g:115:2: blank[collector]
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_blank_in_object361);
        	        blank25=blank(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleobjectEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, blank25.tree);

        	        {
        	             retval.node=  
        	            blank25.node
        	            ;
        	             
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleobjectEx; /* Prevent compiler warnings */
    ruleobjectEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end object */

/**
 * $ANTLR start resource
 * ext/wongi_turtle/Turtle.g:118:1: resource[ VALUE collector ] returns [VALUE node] : ( qname[collector] | uri[collector] );
 */
static TurtleParser_resource_return
resource(pTurtleParser ctx, VALUE collector)
{
    TurtleParser_resource_return retval;

    ANTLR3_UINT32 resource_StartIndex;

    pANTLR3_BASE_TREE root_0;

    TurtleParser_qname_return qname26;
    #undef	RETURN_TYPE_qname26
    #define	RETURN_TYPE_qname26 TurtleParser_qname_return

    TurtleParser_uri_return uri27;
    #undef	RETURN_TYPE_uri27
    #define	RETURN_TYPE_uri27 TurtleParser_uri_return


    /* Initialize rule variables
     */
    resource_StartIndex = INDEX();


    root_0 = NULL;

     VALUE rbDocument = COLLECTOR_DOCUMENT; retval.node= Qnil;
     
    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(14)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    qname26.tree = NULL;

    uri27.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        {
            //  ext/wongi_turtle/Turtle.g:120:2: ( qname[collector] | uri[collector] )

            ANTLR3_UINT32 alt8;

            alt8=2;

            switch ( LA(1) )
            {
            case QNAME:
            	{
            		alt8=1;
            	}
                break;
            case URI:
            	{
            		alt8=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 8;
                EXCEPTION->state        = 0;


                goto ruleresourceEx;

            }

            switch (alt8)
            {
        	case 1:
        	    // ext/wongi_turtle/Turtle.g:121:2: qname[collector]
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_qname_in_resource386);
        	        qname26=qname(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleresourceEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, qname26.tree);

        	        {
        	             retval.node= rb_funcall( rbDocument, symResource, 1, 
        	            qname26.ruby_uri
        	             );
        	             
        	        }


        	    }
        	    break;
        	case 2:
        	    // ext/wongi_turtle/Turtle.g:122:4: uri[collector]
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_uri_in_resource394);
        	        uri27=uri(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleresourceEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, uri27.tree);

        	        {
        	             retval.node= rb_funcall( rbDocument, symResource, 1, 
        	            uri27.ruby_uri
        	             );
        	             
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleresourceEx; /* Prevent compiler warnings */
    ruleresourceEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end resource */

/**
 * $ANTLR start qname
 * ext/wongi_turtle/Turtle.g:125:1: qname[VALUE collector] returns [VALUE ruby_uri] : qn= QNAME ;
 */
static TurtleParser_qname_return
qname(pTurtleParser ctx, VALUE collector)
{
    TurtleParser_qname_return retval;

    ANTLR3_UINT32 qname_StartIndex;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    qn;

    pANTLR3_BASE_TREE qn_tree;

    /* Initialize rule variables
     */
    qname_StartIndex = INDEX();


    root_0 = NULL;

     retval.ruby_uri= Qnil;
     
    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(15)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    qn       = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    qn_tree   = NULL;


    retval.tree  = NULL;

    {
        // ext/wongi_turtle/Turtle.g:127:2: (qn= QNAME )
        // ext/wongi_turtle/Turtle.g:128:2: qn= QNAME
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            qn = (pANTLR3_COMMON_TOKEN) MATCHT(QNAME, &FOLLOW_QNAME_in_qname422);
            if  (HASEXCEPTION())
            {
                goto ruleqnameEx;
            }

            qn_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, qn));
            ADAPTOR->addChild(ADAPTOR, root_0, qn_tree);


            {

                		VALUE rbDocument = COLLECTOR_DOCUMENT;
                		VALUE qnStr = rb_str_new2( (qn->getText(qn))->chars );
                		VALUE split = rb_funcall( qnStr, symSplit, 1, rb_str_new2(":") );
                		VALUE prefixURI = rb_funcall( collector, symLookup, 1, rb_ary_entry( split, 0 ) );
                		VALUE localStr = rb_ary_entry( split, 1 );
                		
                		//  Ruby URI replaces the whole last segment when it ends with a #
                		//  but this screws up the entire namespacing.
                		//  To avoid this, we prepend # to the local part.
                		if( prefixURI == Qnil ) {
                			rb_raise( rb_eException, "Unknown prefix %s", RSTRING_PTR( rb_ary_entry( split, 0 ) ) );
                		}
                		//VALUE hash_fragment = rb_funcall( prefixURI, symFragment, 0 );
                		//if( hash_fragment != Qnil ) {
                		//  localStr = rb_funcall( rb_str_new2("#"), symPLUS, 1, localStr );
                		//} 
                		
                		
                retval.ruby_uri= rb_funcall(
                			cURI, symParse, 1, rb_funcall(
                				cURI, symEscape, 1, rb_funcall(
                					rb_funcall( prefixURI, rb_intern("to_s"), 0 ), symPLUS, 1, localStr
                				)
                			)
                		);

                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleqnameEx; /* Prevent compiler warnings */
    ruleqnameEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end qname */

/**
 * $ANTLR start blank
 * ext/wongi_turtle/Turtle.g:157:1: blank[VALUE collector] returns [VALUE node] : ( BLANK | '[' ( predicate_object_list[ collector, $blank.node ] )? ']' | '(' collection[collector] ')' );
 */
static TurtleParser_blank_return
blank(pTurtleParser ctx, VALUE collector)
{
    TurtleParser_blank_return retval;

    ANTLR3_UINT32 blank_StartIndex;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    BLANK28;
    pANTLR3_COMMON_TOKEN    char_literal29;
    pANTLR3_COMMON_TOKEN    char_literal31;
    pANTLR3_COMMON_TOKEN    char_literal32;
    pANTLR3_COMMON_TOKEN    char_literal34;
    TurtleParser_predicate_object_list_return predicate_object_list30;
    #undef	RETURN_TYPE_predicate_object_list30
    #define	RETURN_TYPE_predicate_object_list30 TurtleParser_predicate_object_list_return

    TurtleParser_collection_return collection33;
    #undef	RETURN_TYPE_collection33
    #define	RETURN_TYPE_collection33 TurtleParser_collection_return

    pANTLR3_BASE_TREE BLANK28_tree;
    pANTLR3_BASE_TREE char_literal29_tree;
    pANTLR3_BASE_TREE char_literal31_tree;
    pANTLR3_BASE_TREE char_literal32_tree;
    pANTLR3_BASE_TREE char_literal34_tree;

    /* Initialize rule variables
     */
    blank_StartIndex = INDEX();


    root_0 = NULL;

     retval.node= Qnil;
     
    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(16)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    BLANK28       = NULL;
    char_literal29       = NULL;
    char_literal31       = NULL;
    char_literal32       = NULL;
    char_literal34       = NULL;
    predicate_object_list30.tree = NULL;

    collection33.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    BLANK28_tree   = NULL;
    char_literal29_tree   = NULL;
    char_literal31_tree   = NULL;
    char_literal32_tree   = NULL;
    char_literal34_tree   = NULL;


    retval.tree  = NULL;

    {
        {
            //  ext/wongi_turtle/Turtle.g:159:2: ( BLANK | '[' ( predicate_object_list[ collector, $blank.node ] )? ']' | '(' collection[collector] ')' )

            ANTLR3_UINT32 alt10;

            alt10=3;

            switch ( LA(1) )
            {
            case BLANK:
            	{
            		alt10=1;
            	}
                break;
            case 17:
            	{
            		alt10=2;
            	}
                break;
            case 10:
            	{
            		alt10=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 10;
                EXCEPTION->state        = 0;


                goto ruleblankEx;

            }

            switch (alt10)
            {
        	case 1:
        	    // ext/wongi_turtle/Turtle.g:160:2: BLANK
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        BLANK28 = (pANTLR3_COMMON_TOKEN) MATCHT(BLANK, &FOLLOW_BLANK_in_blank448);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleblankEx;
        	        }

        	        BLANK28_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, BLANK28));
        	        ADAPTOR->addChild(ADAPTOR, root_0, BLANK28_tree);


        	        {

        	            		VALUE id = rb_str_new2( (BLANK28->getText(BLANK28))->chars );
        	            		
        	            retval.node= rb_funcall( collector, symImportBlank, 1, id );

        	            	
        	        }


        	    }
        	    break;
        	case 2:
        	    // ext/wongi_turtle/Turtle.g:165:3: '[' ( predicate_object_list[ collector, $blank.node ] )? ']'
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        {

        	            			VALUE rbDocument = COLLECTOR_DOCUMENT;
        	            			retval.node= rb_funcall( rbDocument, symBlank, 1, Qnil );

        	            		
        	        }


        	        char_literal29 = (pANTLR3_COMMON_TOKEN) MATCHT(17, &FOLLOW_17_in_blank461);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleblankEx;
        	        }

        	        char_literal29_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal29));
        	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal29_tree);


        	        // ext/wongi_turtle/Turtle.g:169:7: ( predicate_object_list[ collector, $blank.node ] )?
        	        {
        	            int alt9=2;
        	            switch ( LA(1) )
        	            {
        	                case QNAME:
        	                case URI:
        	                case 19:
        	                	{
        	                		alt9=1;
        	                	}
        	                    break;
        	            }

        	            switch (alt9)
        	            {
        	        	case 1:
        	        	    // ext/wongi_turtle/Turtle.g:169:7: predicate_object_list[ collector, $blank.node ]
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_predicate_object_list_in_blank463);
        	        	        predicate_object_list30=predicate_object_list(ctx, collector, 
        	        	        retval.node
        	        	        );

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleblankEx;
        	        	        }

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, predicate_object_list30.tree);

        	        	    }
        	        	    break;

        	            }
        	        }

        	        char_literal31 = (pANTLR3_COMMON_TOKEN) MATCHT(18, &FOLLOW_18_in_blank467);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleblankEx;
        	        }

        	        char_literal31_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal31));
        	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal31_tree);


        	    }
        	    break;
        	case 3:
        	    // ext/wongi_turtle/Turtle.g:171:3: '(' collection[collector] ')'
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        char_literal32 = (pANTLR3_COMMON_TOKEN) MATCHT(10, &FOLLOW_10_in_blank474);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleblankEx;
        	        }

        	        char_literal32_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal32));
        	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal32_tree);


        	        FOLLOWPUSH(FOLLOW_collection_in_blank476);
        	        collection33=collection(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleblankEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, collection33.tree);

        	        char_literal34 = (pANTLR3_COMMON_TOKEN) MATCHT(11, &FOLLOW_11_in_blank479);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleblankEx;
        	        }

        	        char_literal34_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal34));
        	        ADAPTOR->addChild(ADAPTOR, root_0, char_literal34_tree);


        	        {

        	            			retval.node= 
        	            collection33.node
        	            ;

        	            		
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleblankEx; /* Prevent compiler warnings */
    ruleblankEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end blank */

/**
 * $ANTLR start collection
 * ext/wongi_turtle/Turtle.g:177:1: collection[VALUE collector] returns [VALUE node] : (| object[collector] subseq= collection[collector] );
 */
static TurtleParser_collection_return
collection(pTurtleParser ctx, VALUE collector)
{
    TurtleParser_collection_return retval;

    ANTLR3_UINT32 collection_StartIndex;

    pANTLR3_BASE_TREE root_0;

    TurtleParser_collection_return subseq;
    #undef	RETURN_TYPE_subseq
    #define	RETURN_TYPE_subseq TurtleParser_collection_return

    TurtleParser_object_return object35;
    #undef	RETURN_TYPE_object35
    #define	RETURN_TYPE_object35 TurtleParser_object_return


    /* Initialize rule variables
     */
    collection_StartIndex = INDEX();


    root_0 = NULL;


    		VALUE rbDocument = COLLECTOR_DOCUMENT;
    		retval.node= Qnil;

    	
    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(17)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    subseq.tree = NULL;

    object35.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        {
            //  ext/wongi_turtle/Turtle.g:182:2: (| object[collector] subseq= collection[collector] )

            ANTLR3_UINT32 alt11;

            alt11=2;

            switch ( LA(1) )
            {
            case 11:
            	{
            		alt11=1;
            	}
                break;
            case BLANK:
            case QNAME:
            case URI:
            case 10:
            case 17:
            	{
            		alt11=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 11;
                EXCEPTION->state        = 0;


                goto rulecollectionEx;

            }

            switch (alt11)
            {
        	case 1:
        	    // ext/wongi_turtle/Turtle.g:183:3: 
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        {

        	            			rb_funcall( rbDocument, symCommonEXCL, 0 );
        	            			retval.node= rb_funcall( rbDocument, symResource, 1, rb_str_new2(RDF_NIL) );

        	            		
        	        }


        	    }
        	    break;
        	case 2:
        	    // ext/wongi_turtle/Turtle.g:188:3: object[collector] subseq= collection[collector]
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_object_in_collection514);
        	        object35=object(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecollectionEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, object35.tree);

        	        {

        	            			retval.node= rb_funcall( rbDocument, symBlank, 1, Qnil );

        	            			VALUE first = rb_funcall( rbDocument, symResource, 1, rb_str_new2(RDF_FIRST) );
        	            			VALUE argv[] = { retval.node
        	            , first, object35.node
        	             };
        	            			VALUE statement = rb_class_new_instance( 3, argv, cStatement );
        	            			rb_funcall( rbDocument, symLSHIFT, 1, statement );
        	            		
        	        }


        	        FOLLOWPUSH(FOLLOW_collection_in_collection525);
        	        subseq=collection(ctx, collector);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecollectionEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, subseq.tree);

        	        {

        	            			VALUE rest = rb_funcall( rbDocument, symResource, 1, rb_str_new2(RDF_REST) );
        	            			VALUE argv[] = { retval.node
        	            , rest, subseq.node
        	             };
        	            			VALUE statement = rb_class_new_instance( 3, argv, cStatement );
        	            			rb_funcall( rbDocument, symLSHIFT, 1, statement );
        	            		
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulecollectionEx; /* Prevent compiler warnings */
    rulecollectionEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end collection */

/**
 * $ANTLR start uri
 * ext/wongi_turtle/Turtle.g:205:1: uri[VALUE collector] returns [VALUE ruby_uri] : URI ;
 */
static TurtleParser_uri_return
uri(pTurtleParser ctx, VALUE collector)
{
    TurtleParser_uri_return retval;

    ANTLR3_UINT32 uri_StartIndex;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    URI36;

    pANTLR3_BASE_TREE URI36_tree;

    /* Initialize rule variables
     */
    uri_StartIndex = INDEX();


    root_0 = NULL;

     retval.ruby_uri= Qnil;
     
    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(18)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    URI36       = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    URI36_tree   = NULL;


    retval.tree  = NULL;

    {
        // ext/wongi_turtle/Turtle.g:207:2: ( URI )
        // ext/wongi_turtle/Turtle.g:207:4: URI
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            URI36 = (pANTLR3_COMMON_TOKEN) MATCHT(URI, &FOLLOW_URI_in_uri551);
            if  (HASEXCEPTION())
            {
                goto ruleuriEx;
            }

            URI36_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, URI36));
            ADAPTOR->addChild(ADAPTOR, root_0, URI36_tree);


            {

                		pANTLR3_STRING str = (URI36->getText(URI36)) /*(URI36->getText(URI36))->toUTF8((URI36->getText(URI36)))*/ ;
                		VALUE rb_strUri = rb_str_new2( str->chars );
                		
                retval.ruby_uri= rb_funcall( cURI, symParse, 1, rb_funcall( cURI, symEscape, 1, rb_strUri ) );


                		if( ! rb_funcall(retval.ruby_uri
                , symAbsoluteQ, 0) ) {
                			//  relative uri encountered
                			//  document must have a base
                			VALUE rbDocument = COLLECTOR_DOCUMENT;
                			VALUE rbBase = rb_funcall(rbDocument, symBase, 0 );
                			if( rbBase == Qnil ) {
                				rb_raise( rb_eException, "Relative URI with no base" );
                			}
                			else {
                				retval.ruby_uri= rb_funcall( rbBase, symPLUS, 1, 
                retval.ruby_uri
                 );

                			}

                		}

                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleuriEx; /* Prevent compiler warnings */
    ruleuriEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end uri */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
