/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ext/wongi_turtle/Turtle.g
 *     -                            On : 2012-07-20 11:41:35
 *     -                 for the lexer : TurtleLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

	#include <ruby.h>

/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "TurtleLexer.h"
/* ----------------------------------------- */


/** String literals used by TurtleLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x40, 0x62, 0x61, 0x73, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x40, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x5F, 0x3A,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pTurtleLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pTurtleLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pTurtleLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pTurtleLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mT__10    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mT__11    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mT__12    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mT__13    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mT__14    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mT__15    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mT__16    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mT__17    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mT__18    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mT__19    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mURI    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mIDENT    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mQNAME    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mPREFIX    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mBLANK    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (pTurtleLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pTurtleLexer ctx);
static void	TurtleLexerFree(pTurtleLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
TurtleLexerFree  (pTurtleLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
TurtleLexerReset (pTurtleLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "ext/wongi_turtle/Turtle.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called TurtleLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pTurtleLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pTurtleLexer TurtleLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return TurtleLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called TurtleLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pTurtleLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pTurtleLexer TurtleLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pTurtleLexer ctx; // Context structure we will build and return

    ctx = (pTurtleLexer) ANTLR3_CALLOC(1, sizeof(TurtleLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in TurtleLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our TurtleLexer interface
     */
    ctx->mT__10	= mT__10;
    ctx->mT__11	= mT__11;
    ctx->mT__12	= mT__12;
    ctx->mT__13	= mT__13;
    ctx->mT__14	= mT__14;
    ctx->mT__15	= mT__15;
    ctx->mT__16	= mT__16;
    ctx->mT__17	= mT__17;
    ctx->mT__18	= mT__18;
    ctx->mT__19	= mT__19;
    ctx->mURI	= mURI;
    ctx->mIDENT	= mIDENT;
    ctx->mQNAME	= mQNAME;
    ctx->mPREFIX	= mPREFIX;
    ctx->mBLANK	= mBLANK;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= TurtleLexerFree;
    ctx->reset          = TurtleLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}

/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( T__10 | T__11 | T__12 | T__13 | T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | URI | IDENT | QNAME | PREFIX | BLANK | WS );
 */
static const ANTLR3_INT32 dfa4_eot[22] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, 16, -1, 19, -1, -1, -1, -1, -1, 19, 
	21, -1, -1, -1
    };
static const ANTLR3_INT32 dfa4_eof[22] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa4_min[22] =
    {
	9, -1, -1, -1, -1, -1, 98, -1, -1, 45, -1, 45, -1, -1, -1, -1, -1, 45, 
	65, -1, -1, -1
    };
static const ANTLR3_INT32 dfa4_max[22] =
    {
	122, -1, -1, -1, -1, -1, 112, -1, -1, 122, -1, 122, -1, -1, -1, -1, -1, 
	122, 122, -1, -1, -1
    };
static const ANTLR3_INT32 dfa4_accept[22] =
    {
	-1, 1, 2, 3, 4, 5, -1, 8, 9, -1, 11, -1, 15, 16, 6, 7, 10, -1, -1, 12, 
	13, 14
    };
static const ANTLR3_INT32 dfa4_special[22] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa4_T_empty	    NULL

static const ANTLR3_INT32 dfa4_T0[] =
    {
	20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 
	20, 20, 20, 20, 20, 20, 20, 20, -1, -1, -1, -1, -1, -1, 20, 20, 20, 20, 
	20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 
	20, 20, 20, 20
    };

static const ANTLR3_INT32 dfa4_T1[] =
    {
	13, 13, -1, -1, 13, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 13, -1, -1, -1, -1, -1, -1, -1, 1, 2, -1, -1, 3, -1, 
	4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 5, 10, -1, -1, -1, 6, 
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
	11, 11, 11, 11, 11, 11, 11, 11, 7, -1, 8, -1, 12, -1, 9, 11, 11, 11, 11, 
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
	11, 11, 11
    };

static const ANTLR3_INT32 dfa4_T2[] =
    {
	17, -1, -1, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, -1, -1, -1, -1, 
	-1, -1, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
	17, 17, 17, 17, 17, 17, 17, 17, 17, 17, -1, -1, -1, -1, 17, -1, 17, 17, 
	17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
	17, 17, 17, 17, 17, 17
    };

static const ANTLR3_INT32 dfa4_T3[] =
    {
	14, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 15
    };


/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa4_transitions[] =
{
    dfa4_T1, NULL, NULL, NULL, NULL, NULL, dfa4_T3, NULL, NULL, dfa4_T2, 
    NULL, dfa4_T2, NULL, NULL, NULL, NULL, NULL, dfa4_T2, dfa4_T0, NULL, 
    NULL, NULL
};


/* Declare tracking structure for Cyclic DFA 4
 */
static
ANTLR3_CYCLIC_DFA cdfa4
    =	{
	    4,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"1:1: Tokens : ( T__10 | T__11 | T__12 | T__13 | T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | URI | IDENT | QNAME | PREFIX | BLANK | WS );",
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/

	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa4_eot,	    /* EOT table			    */
	    dfa4_eof,	    /* EOF table			    */
	    dfa4_min,	    /* Minimum tokens for each state    */
	    dfa4_max,	    /* Maximum tokens for each state    */
	    dfa4_accept,	/* Accept table			    */
	    dfa4_special,	/* Special transition states	    */
	    dfa4_transitions	/* Table of transition tables	    */

	};
/* End of Cyclic DFA 4
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 11:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__10
 *
 * Looks to match the characters the constitute the token T__10
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__10(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__10;


    // ext/wongi_turtle/Turtle.g:11:7: ( '(' )
    // ext/wongi_turtle/Turtle.g:11:9: '('
    {
        MATCHC('(');
        if  (HASEXCEPTION())
        {
            goto ruleT__10Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__10Ex; /* Prevent compiler warnings */
    ruleT__10Ex: ;

}
// $ANTLR end T__10

//   Comes from: 12:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__11
 *
 * Looks to match the characters the constitute the token T__11
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__11(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__11;


    // ext/wongi_turtle/Turtle.g:12:7: ( ')' )
    // ext/wongi_turtle/Turtle.g:12:9: ')'
    {
        MATCHC(')');
        if  (HASEXCEPTION())
        {
            goto ruleT__11Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__11Ex; /* Prevent compiler warnings */
    ruleT__11Ex: ;

}
// $ANTLR end T__11

//   Comes from: 13:7: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__12
 *
 * Looks to match the characters the constitute the token T__12
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__12(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__12;


    // ext/wongi_turtle/Turtle.g:13:7: ( ',' )
    // ext/wongi_turtle/Turtle.g:13:9: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleT__12Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__12Ex; /* Prevent compiler warnings */
    ruleT__12Ex: ;

}
// $ANTLR end T__12

//   Comes from: 14:7: ( '.' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__13
 *
 * Looks to match the characters the constitute the token T__13
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__13(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__13;


    // ext/wongi_turtle/Turtle.g:14:7: ( '.' )
    // ext/wongi_turtle/Turtle.g:14:9: '.'
    {
        MATCHC('.');
        if  (HASEXCEPTION())
        {
            goto ruleT__13Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__13Ex; /* Prevent compiler warnings */
    ruleT__13Ex: ;

}
// $ANTLR end T__13

//   Comes from: 15:7: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__14
 *
 * Looks to match the characters the constitute the token T__14
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__14(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__14;


    // ext/wongi_turtle/Turtle.g:15:7: ( ';' )
    // ext/wongi_turtle/Turtle.g:15:9: ';'
    {
        MATCHC(';');
        if  (HASEXCEPTION())
        {
            goto ruleT__14Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__14Ex; /* Prevent compiler warnings */
    ruleT__14Ex: ;

}
// $ANTLR end T__14

//   Comes from: 16:7: ( '@base' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__15
 *
 * Looks to match the characters the constitute the token T__15
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__15(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__15;


    // ext/wongi_turtle/Turtle.g:16:7: ( '@base' )
    // ext/wongi_turtle/Turtle.g:16:9: '@base'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleT__15Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__15Ex; /* Prevent compiler warnings */
    ruleT__15Ex: ;

}
// $ANTLR end T__15

//   Comes from: 17:7: ( '@prefix' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__16
 *
 * Looks to match the characters the constitute the token T__16
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__16(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__16;


    // ext/wongi_turtle/Turtle.g:17:7: ( '@prefix' )
    // ext/wongi_turtle/Turtle.g:17:9: '@prefix'
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleT__16Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__16Ex; /* Prevent compiler warnings */
    ruleT__16Ex: ;

}
// $ANTLR end T__16

//   Comes from: 18:7: ( '[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__17
 *
 * Looks to match the characters the constitute the token T__17
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__17(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__17;


    // ext/wongi_turtle/Turtle.g:18:7: ( '[' )
    // ext/wongi_turtle/Turtle.g:18:9: '['
    {
        MATCHC('[');
        if  (HASEXCEPTION())
        {
            goto ruleT__17Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__17Ex; /* Prevent compiler warnings */
    ruleT__17Ex: ;

}
// $ANTLR end T__17

//   Comes from: 19:7: ( ']' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__18
 *
 * Looks to match the characters the constitute the token T__18
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__18(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__18;


    // ext/wongi_turtle/Turtle.g:19:7: ( ']' )
    // ext/wongi_turtle/Turtle.g:19:9: ']'
    {
        MATCHC(']');
        if  (HASEXCEPTION())
        {
            goto ruleT__18Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__18Ex; /* Prevent compiler warnings */
    ruleT__18Ex: ;

}
// $ANTLR end T__18

//   Comes from: 20:7: ( 'a' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__19
 *
 * Looks to match the characters the constitute the token T__19
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__19(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__19;


    // ext/wongi_turtle/Turtle.g:20:7: ( 'a' )
    // ext/wongi_turtle/Turtle.g:20:9: 'a'
    {
        MATCHC('a');
        if  (HASEXCEPTION())
        {
            goto ruleT__19Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__19Ex; /* Prevent compiler warnings */
    ruleT__19Ex: ;

}
// $ANTLR end T__19

//   Comes from: 225:2: ( '<' (uri=~ ( '>' ) )* '>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start URI
 *
 * Looks to match the characters the constitute the token URI
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mURI(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;
    ANTLR3_UINT32 uri;


    _type	    = URI;


    // ext/wongi_turtle/Turtle.g:225:2: ( '<' (uri=~ ( '>' ) )* '>' )
    // ext/wongi_turtle/Turtle.g:226:2: '<' (uri=~ ( '>' ) )* '>'
    {
        MATCHC('<');
        if  (HASEXCEPTION())
        {
            goto ruleURIEx;
        }


        // ext/wongi_turtle/Turtle.g:226:9: (uri=~ ( '>' ) )*

        for (;;)
        {
            int alt1=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA1_0 = LA(1);
                if ( (((LA1_0 >= 0x0000) && (LA1_0 <= '=')) || ((LA1_0 >= '?') && (LA1_0 <= 0xFFFF))))
                {
                    alt1=1;
                }

            }
            switch (alt1)
            {
        	case 1:
        	    // ext/wongi_turtle/Turtle.g:226:9: uri=~ ( '>' )
        	    {
        	        uri= LA(1);

        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '=')) || ((LA(1) >= '?') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleURIEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop1;	/* break out of the loop */
        	    break;
            }
        }
        loop1: ; /* Jump out to here if this rule does not match */


        MATCHC('>');
        if  (HASEXCEPTION())
        {
            goto ruleURIEx;
        }


        {

            		pANTLR3_STRING text, sub;
            		text = GETTEXT();
            		sub = text->subString(text, 1, text->len-2 ); //  all but first and last; for some reason we need to use -2 in antlr 3.4.. investigate
            		SETTEXT( sub );
            		//printf("extracted URI = %s\n", GETTEXT()->chars );
            	
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleURIEx; /* Prevent compiler warnings */
    ruleURIEx: ;

}
// $ANTLR end URI

//   Comes from: 237:2: ( ( 'a' .. 'z' | 'A' .. 'Z' ) ( 'A' .. 'Z' | '_' | 'a' .. 'z' | '-' | '0' .. '9' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start IDENT
 *
 * Looks to match the characters the constitute the token IDENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mIDENT(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = IDENT;


    // ext/wongi_turtle/Turtle.g:237:2: ( ( 'a' .. 'z' | 'A' .. 'Z' ) ( 'A' .. 'Z' | '_' | 'a' .. 'z' | '-' | '0' .. '9' )* )
    // ext/wongi_turtle/Turtle.g:238:2: ( 'a' .. 'z' | 'A' .. 'Z' ) ( 'A' .. 'Z' | '_' | 'a' .. 'z' | '-' | '0' .. '9' )*
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleIDENTEx;
        }


        // ext/wongi_turtle/Turtle.g:242:2: ( 'A' .. 'Z' | '_' | 'a' .. 'z' | '-' | '0' .. '9' )*

        for (;;)
        {
            int alt2=2;
            switch ( LA(1) )
            {
            case '-':
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            	{
            		alt2=1;
            	}
                break;

            }

            switch (alt2)
            {
        	case 1:
        	    // ext/wongi_turtle/Turtle.g:
        	    {
        	        if ( LA(1) == '-' || ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleIDENTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop2;	/* break out of the loop */
        	    break;
            }
        }
        loop2: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIDENTEx; /* Prevent compiler warnings */
    ruleIDENTEx: ;

}
// $ANTLR end IDENT

//   Comes from: 251:7: ( IDENT ':' IDENT )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start QNAME
 *
 * Looks to match the characters the constitute the token QNAME
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mQNAME(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = QNAME;


    // ext/wongi_turtle/Turtle.g:251:7: ( IDENT ':' IDENT )
    // ext/wongi_turtle/Turtle.g:251:9: IDENT ':' IDENT
    {
        /* 251:9: IDENT ':' IDENT */
        mIDENT(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleQNAMEEx;
        }



        MATCHC(':');
        if  (HASEXCEPTION())
        {
            goto ruleQNAMEEx;
        }


        /* 251:9: IDENT ':' IDENT */
        mIDENT(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleQNAMEEx;
        }



    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleQNAMEEx; /* Prevent compiler warnings */
    ruleQNAMEEx: ;

}
// $ANTLR end QNAME

//   Comes from: 253:8: (ident= IDENT ':' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PREFIX
 *
 * Looks to match the characters the constitute the token PREFIX
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPREFIX(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;
    pANTLR3_COMMON_TOKEN ident;


    ident = NULL;

    _type	    = PREFIX;


    // ext/wongi_turtle/Turtle.g:253:8: (ident= IDENT ':' )
    // ext/wongi_turtle/Turtle.g:253:10: ident= IDENT ':'
    {
        /* 253:10: ident= IDENT ':' */
        {
            ANTLR3_MARKER identStart220 = GETCHARINDEX();
        mIDENT(ctx );
            if  (HASEXCEPTION())
            {
                goto rulePREFIXEx;
            }

            ident = LEXSTATE->tokFactory->newToken(LEXSTATE->tokFactory);
            ident->setType(ident, ANTLR3_TOKEN_INVALID);
            ident->setStartIndex(ident, identStart220);
            ident->setStopIndex(ident, GETCHARINDEX()-1);
            ident->input = INPUT;
        }


        MATCHC(':');
        if  (HASEXCEPTION())
        {
            goto rulePREFIXEx;
        }


        {

            		SETTEXT( ident->getText(ident) );
            	
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePREFIXEx; /* Prevent compiler warnings */
    rulePREFIXEx: ;

    ident = NULL;

}
// $ANTLR end PREFIX

//   Comes from: 259:7: ( '_:' ident= IDENT )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BLANK
 *
 * Looks to match the characters the constitute the token BLANK
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBLANK(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;
    pANTLR3_COMMON_TOKEN ident;


    ident = NULL;

    _type	    = BLANK;


    // ext/wongi_turtle/Turtle.g:259:7: ( '_:' ident= IDENT )
    // ext/wongi_turtle/Turtle.g:260:2: '_:' ident= IDENT
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleBLANKEx;
        }




        /* 260:2: '_:' ident= IDENT */
        {
            ANTLR3_MARKER identStart240 = GETCHARINDEX();
        mIDENT(ctx );
            if  (HASEXCEPTION())
            {
                goto ruleBLANKEx;
            }

            ident = LEXSTATE->tokFactory->newToken(LEXSTATE->tokFactory);
            ident->setType(ident, ANTLR3_TOKEN_INVALID);
            ident->setStartIndex(ident, identStart240);
            ident->setStopIndex(ident, GETCHARINDEX()-1);
            ident->input = INPUT;
        }


        {

            		SETTEXT( ident->getText(ident) );
            	
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleBLANKEx; /* Prevent compiler warnings */
    ruleBLANKEx: ;

    ident = NULL;

}
// $ANTLR end BLANK

//   Comes from: 267:2: ( ( ' ' | '\\t' | '\\r' | '\\n' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pTurtleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // ext/wongi_turtle/Turtle.g:267:2: ( ( ' ' | '\\t' | '\\r' | '\\n' )+ )
    // ext/wongi_turtle/Turtle.g:268:2: ( ' ' | '\\t' | '\\r' | '\\n' )+
    {
        // ext/wongi_turtle/Turtle.g:268:2: ( ' ' | '\\t' | '\\r' | '\\n' )+
        {
            int cnt3=0;

            for (;;)
            {
                int alt3=2;
        	switch ( LA(1) )
        	{
        	case '\t':
        	case '\n':
        	case '\r':
        	case ' ':
        		{
        			alt3=1;
        		}
        	    break;

        	}

        	switch (alt3)
        	{
        	    case 1:
        	        // ext/wongi_turtle/Turtle.g:
        	        {
        	            if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt3 >= 1 )
        		{
        		    goto loop3;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt3++;
            }
            loop3: ;	/* Jump to here if this rule does not match */
        }

        {

            		LEXSTATE->channel=HIDDEN;
            	
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pTurtleLexer ctx)
{
    {
        //  ext/wongi_turtle/Turtle.g:1:8: ( T__10 | T__11 | T__12 | T__13 | T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | URI | IDENT | QNAME | PREFIX | BLANK | WS )

        ANTLR3_UINT32 alt4;

        alt4=16;

        alt4 = cdfa4.predict(ctx, RECOGNIZER, ISTREAM, &cdfa4);
        if  (HASEXCEPTION())
        {
            goto ruleTokensEx;
        }

        switch (alt4)
        {
    	case 1:
    	    // ext/wongi_turtle/Turtle.g:1:10: T__10
    	    {
    	        /* 1:10: T__10 */
    	        mT__10(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // ext/wongi_turtle/Turtle.g:1:16: T__11
    	    {
    	        /* 1:16: T__11 */
    	        mT__11(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // ext/wongi_turtle/Turtle.g:1:22: T__12
    	    {
    	        /* 1:22: T__12 */
    	        mT__12(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // ext/wongi_turtle/Turtle.g:1:28: T__13
    	    {
    	        /* 1:28: T__13 */
    	        mT__13(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // ext/wongi_turtle/Turtle.g:1:34: T__14
    	    {
    	        /* 1:34: T__14 */
    	        mT__14(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // ext/wongi_turtle/Turtle.g:1:40: T__15
    	    {
    	        /* 1:40: T__15 */
    	        mT__15(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // ext/wongi_turtle/Turtle.g:1:46: T__16
    	    {
    	        /* 1:46: T__16 */
    	        mT__16(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // ext/wongi_turtle/Turtle.g:1:52: T__17
    	    {
    	        /* 1:52: T__17 */
    	        mT__17(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // ext/wongi_turtle/Turtle.g:1:58: T__18
    	    {
    	        /* 1:58: T__18 */
    	        mT__18(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // ext/wongi_turtle/Turtle.g:1:64: T__19
    	    {
    	        /* 1:64: T__19 */
    	        mT__19(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // ext/wongi_turtle/Turtle.g:1:70: URI
    	    {
    	        /* 1:70: URI */
    	        mURI(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // ext/wongi_turtle/Turtle.g:1:74: IDENT
    	    {
    	        /* 1:74: IDENT */
    	        mIDENT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // ext/wongi_turtle/Turtle.g:1:80: QNAME
    	    {
    	        /* 1:80: QNAME */
    	        mQNAME(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // ext/wongi_turtle/Turtle.g:1:86: PREFIX
    	    {
    	        /* 1:86: PREFIX */
    	        mPREFIX(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // ext/wongi_turtle/Turtle.g:1:93: BLANK
    	    {
    	        /* 1:93: BLANK */
    	        mBLANK(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // ext/wongi_turtle/Turtle.g:1:99: WS
    	    {
    	        /* 1:99: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
